### ISSUE TITLE
Stránka s nápovědou

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/e-ilustrace#10]
Vytvořit separátní stránku ve WP

**Comment by VojtechSicha** [comment]
@Kretiss @macholiver Prosím přesměrovat Nápovědu z app (https://app.e-ilustrace.cz/fe/src/components/sidebar#) na stránky projektu, kde už ji postupně vytváříme (https://e-ilustrace.cz/napoveda/).

**Comment by VojtechSicha** [comment]
@Kretiss ANO: https://e-ilustrace.cz/en/help/

**Comment by VojtechSicha** [comment]
@macholiver Může na produkci. Předem díky.
