### ISSUE TITLE
VÝSTAVY - Editační prostředí - autor

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#101]
@Kretiss Chybí okno pro vyplnění údajů o autoru výstavy

**Comment by Kretiss** [comment]
@macholiver Máme to na BE do čeho ukládat?

**Comment by macholiver** [comment]
@VojtechSicha 
Prosim o doplnenie o ake udaje sa konkretne jedna. (meno, priezvisko, datum narodenia... ?)

**Comment by VojtechSicha** [comment]
@macholiver Stačí jen jméno a příjmení.

**Comment by Kretiss** [comment]
@VojtechSicha  @macholiver Jméno a příjmení se vyplňuje při registraci, tím pádem to nemusíme doplňovat, stačí propsat data o uživateli na FE

**Comment by macholiver** [comment]
@Kretiss done

**Comment by VojtechSicha** [comment]
@Kretiss Ještě by stálo zato pořešit umístění informací o autorovi. Motá se to s textem případného úvodu.

@mach Může na produkci.

**Comment by macholiver** [comment]
@VojtechSicha Nasadene na produkciu

**Comment by VojtechSicha** [comment]
@macholiver @Kretiss Pardon, tak u toho autora je ještě jeden nedostatek. Na slidu výstavy se zobrazuje místo jména uiid viz

![Autor na slidu](https://github.com/LIBCAS/e-ilustrace/assets/127321356/d977b7ab-74e6-498b-a668-c6d250a43f79)

**Comment by VojtechSicha** [comment]
@ Může na produkci
