### ISSUE TITLE
VÝSTAVY - Editační prostředí: možnosti prezentace

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#102]
@Kretiss Nastavení primárního zobrazení výstavy autorem (album, slider, storyline) - album a slider slité v jedno.

**Comment by Kretiss** [comment]
@macholiver Tady nám chybí v enumu ten jeden typ `SLIDER`

`type Radio = "ALBUM" | "STORYLINE";`

**Comment by macholiver** [comment]
@Kretiss done

**Comment by VojtechSicha** [comment]
@macholiver V pořádku, může na produkci.
