### ISSUE TITLE
VÝSTAVY - Editační prostředí: úvodní obrázek

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#103]
@Kretiss  chybí možnost vybrat, který obrázek bude zastupovat celou výstavu.

**Comment by Kretiss** [comment]
@macholiver můžeš na BE prosím tě přidat nějaký atribut, kterým se nastaví nějaká ilustrace jako výchozí? Ať podle toho můžu zobrazit ten obrázek

**Comment by macholiver** [comment]
@Kretiss boolean ExhibitionItem.preface

**Comment by VojtechSicha** [comment]
@macholiver V pořádku, může jít na produkci.

**Comment by macholiver** [comment]
@VojtechSicha Nasadene na produkciu
