### ISSUE TITLE
VÝSTAVY - Editační prostředí: pohyb v editaci

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#105]
@Kretiss 

umožnit kromě posouvání šipkami také přetahování ilustrací pomocí dropování

umožnit otevření záznamu ilustrace proklikem z náhledu v editaci, a to v novém okně.

**Comment by Kretiss** [comment]
Tady jsem přidal ten proklik, pohyb pomocí dropování řešit nebudeme

**Comment by VojtechSicha** [comment]
@Kretiss V pořádku, drop necháme být. Na testu vidím možnost prokliknout se do záznamu přes název. Přijde mi to v ok. Takže bych to poslal na produkci.

**Comment by macholiver** [comment]
@VojtechSicha nasadene

**Comment by VojtechSicha** [comment]
@macholiver Ok.
