### ISSUE TITLE
VÝSTAVY - Editační prostředí: upozornění na neuloženou práci

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#106]
@Kretiss 
vyskočí bublina: Vaše změny nebyly uloženy již 15 minut.
obdobný text na konci výstavy zrušit

**Comment by VojtechSicha** [comment]
@macholiver V pořádku. Může na produkci.

**Comment by macholiver** [comment]
@VojtechSicha Nasadene na produkciu
