### ISSUE TITLE
TÉMATA

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#110]
@Kretiss 

u zástupných ikon kategorií přidat Přejít na výstavy (souvisí to)

u ilustrací v jednotlivých kategoriích Přejít na výstavy zrušit

**Comment by VojtechSicha** [comment]
@Kretiss Ano, takto je to správně.
@macholiver Může jít na produkci.

**Comment by macholiver** [comment]
@VojtechSicha Nasadene na produkciu
