### ISSUE TITLE
ICONCLASS - odkazování

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#111]
@Kretiss  IC popis v záznamu by měl fungovat ve dvou směrech

a) když uživatel klikne na kód/heslo, měl by získat výsledek rešerše (být přesměrován), jako při vyhledávání v IC

b) naopak k přesunu na identický kód/heslo v rámci stránky iconclass.org by měla posloužit ikona

Podobně je to řešeno u bibliografických záznamů v portálu knihoveda.cz viz obrázek

![KHVD odkazy](https://github.com/LIBCAS/e-ilustrace/assets/127321356/3f02aa43-d62a-40ee-ad83-61dcda5c9fd1)

Na uvedeném příkladu lupa odkazuje na autoritní záznam, linkované Příjmení a jméno tiskaře vyhledá další související záznamy (v případě EIL další ilustrace) a poslední ikona (v EIL to bude ikona IC) odkazuje na externí online encyklopedii.

**Comment by Kretiss** [comment]
48C161 - column, pillar

kód s názvem půjde do iconclass záložky, za názvem ikona s odkazem na iconclass.org
