### ISSUE TITLE
VYHLEDÁVÁNÍ - počty výskytů

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#112]
@Kretiss  @macholiver 

Několikrát jsme řešili možnost zvýraznění počtů výskytů v nabídce. Zde jsem nasimuloval, jak to mají řešené v katalogu USTC  viz https://www.ustc.ac.uk/

Celkový náhled

![USTC](https://github.com/LIBCAS/e-ilustrace/assets/127321356/4ee9d2f6-ab02-40ab-96c6-1eea5994414c)

Přiblížení

![počty](https://github.com/LIBCAS/e-ilustrace/assets/127321356/ecbfd55d-7c2d-4005-b9f0-a8041948ba12)

Při výběru autora se země vydání dynamicky upraví

![související počty](https://github.com/LIBCAS/e-ilustrace/assets/127321356/053a71bb-0029-4db3-90a5-3cd588a2fc5d)

Takto by to nešlo?

**Comment by Kretiss** [comment]
@macholiver Tady jsme se bavili, že se to taky nebude řešit že?

**Comment by macholiver** [comment]
@Kretiss S aktualnym vykonom appky a prihladnutim na dolezitejsie issues, zatial urcite nie.

**Comment by VojtechSicha** [comment]
@Kretiss @macholiver Myslím, že jsem to sem dával především proto, abychom si ujasnili, co máme vlastně na mysli. Je pravda, že je to uživatelsky opravdu vstřícné. Nicméně dá se bez toho žít, tím spíš, že to app nedává. Zavírám.
