### ISSUE TITLE
Filtrování IIIF

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#113]
@Kretiss filtra podle dostupných obrázků IIIF zatím nefunguje. Viz 
![IIIF](https://github.com/LIBCAS/e-ilustrace/assets/127321356/79591c98-b8f8-4935-8b6a-56593dc6d4be)

**Comment by Kretiss** [comment]
@macholiver Na toto nám chybí atribut na filtrování

**Comment by VojtechSicha** [comment]
@macholiver Může do produkce.
