### ISSUE TITLE
APP Vyhledávání Admin podle stavu zpracování

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#119]
@Kretiss @macholiver Vyhledávání podle stavu nefunguje, jak má. Patrně bude problém v nastavení Obohaceno/neobohaceno viz obrázek. Stav uveden Neobohaceno, ale IC hesla jsou vyplněná.
![Admin obohaceno](https://github.com/LIBCAS/e-ilustrace/assets/127321356/79f6c9d6-0e3d-4a58-a5a6-b67c1182e7a8)

**Comment by Kretiss** [comment]
@VojtechSicha Tady se to pokud si dobře pamatuju nastavuje manuálně ne?

**Comment by VojtechSicha** [comment]
@Kretiss Ano při doplňování hesel IC a Témat zde bude vybírat údaj zpracovatel, tedy někdo z KNAV nebo NK. V aktuální fázi přelití z google tabulky by se ale měla informace NE/OBHACENO získat z té tabulky.

**Comment by Kretiss** [comment]
@macholiver

**Comment by macholiver** [comment]
@VojtechSicha Pridana oprava, aby sa pri importe z .xml od pana Hejzla spravne prepisovali stavy, nutne odsledovat po poslednom import z .xlsx suboru
