### ISSUE TITLE
Stránkování

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/e-ilustrace#12]
- [x] Při zobrazení 1000 ilustrací se stránkuje po 10, nabízí se tedy 100 stránek. Layout se roztahuje moc doprava a rozhazuje stránku.
- [x] Přidat vedle stránkování celkový počet výskytů ilustrací / knih.

**Comment by VojtechSicha** [comment]
@Kretiss  při vstupu do aplikace se z nějakého důvodu v seznamu ilustrací nacházíme rovnou na druhé záložce

**Comment by Kretiss** [comment]
@VojtechSicha Opraveno
