### ISSUE TITLE
APP - Admin vyhledávání facety (Test i APP)

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#120]
@macholiver @Kretiss Facety vyhledávají stejně špatně jako v klasickém vyhledávání. Tzn. nabízejí, co nemají.

**Comment by VojtechSicha** [comment]
@Kretiss  Buď něco dělám špatně nebo fasety v adminovi nevyhledávají.

**Comment by macholiver** [comment]
@VojtechSicha nasadene
