### ISSUE TITLE
APP - Titulní listy z BCBT

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#125]
@macholiver Titulní listy, ještě nejsou v EIL zdaleka všechny, ale postupně se zobrazují ve větším počtu. K 18.1. jich je 18.

**Comment by macholiver** [comment]
https://app.e-ilustrace.cz/record-detail/182b1d39-bd55-4d1f-8962-4214f16ebc0b

**Comment by VojtechSicha** [comment]
@macholiver Pět záznamů, které mají v datech titulní list, ale EIL není.

https://app.e-ilustrace.cz/record-detail/a6cdc9d9-dee7-4190-950d-595a9d961f34/switch?back=search
https://app.e-ilustrace.cz/record-detail/fefe32bf-8b83-4162-b5f8-30d15a0fbbb5/switch?back=search
https://app.e-ilustrace.cz/record-detail/b0dde11e-431d-4ef4-b127-8eab574853a9/switch?back=search
https://app.e-ilustrace.cz/record-detail/c31c1ff0-6fdc-4eb0-be2b-f0ca47a39080/switch?back=search
https://app.e-ilustrace.cz/record-detail/eb7f25bb-e562-41f1-bc37-e0b6693ebe26/switch?back=search

**Comment by VojtechSicha** [comment]
@macholiver Mám přidat další záznamy s chybějícím titulním listem (případně všechny)?

**Comment by VojtechSicha** [comment]
@macholiver Přidávám dalších 15.

https://app.e-ilustrace.cz/record-detail/67a3f77c-4095-4097-bd6c-650f9405bd47/switch?back=search
https://app.e-ilustrace.cz/record-detail/852192f0-aba4-49b9-92c3-64f9387644f6/switch?back=search
https://app.e-ilustrace.cz/record-detail/91a05a10-c088-49f9-b4a3-56712038f45e/switch?back=search
https://app.e-ilustrace.cz/record-detail/72aaeaa7-9e5c-45cd-9fff-133891158129/switch?back=search
https://app.e-ilustrace.cz/record-detail/ca3867ed-c772-4605-a038-58c56f181a9c/switch?back=search
https://app.e-ilustrace.cz/record-detail/bb07e1a9-66e0-469b-b07f-b8c9da3d7246/switch?back=search
https://app.e-ilustrace.cz/record-detail/8510a550-0900-404d-924e-aca1d0188042/switch?back=search
https://app.e-ilustrace.cz/record-detail/cbc71bff-5a3b-43c8-a8da-3d4cd86d0473/switch?back=search
https://app.e-ilustrace.cz/record-detail/4511a07b-583b-4350-a2a4-5a1c955f9f10/switch?back=search
https://app.e-ilustrace.cz/record-detail/7e25084c-bf6f-4847-aa31-c76256958eb6/switch?back=search
https://app.e-ilustrace.cz/record-detail/504072fe-7a80-4565-b506-8a2491c553b8/switch?back=search
https://app.e-ilustrace.cz/record-detail/70dc265d-61a7-4fbe-a7e3-bf3146416b56/switch?back=search
https://app.e-ilustrace.cz/record-detail/ff5a0e4d-f202-4457-8f19-51f878fb3e66/switch?back=search
https://app.e-ilustrace.cz/record-detail/a2d82eaf-6fb3-4574-94a0-a82a0f0e5707/switch?back=search
https://app.e-ilustrace.cz/record-detail/48de49f9-c333-443f-8cb4-052ba9e809d9/switch?back=search

**Comment by VojtechSicha** [comment]
@macholiver Ještě 5.

https://app.e-ilustrace.cz/record-detail/3c3736c2-3668-483d-9062-b01be1a6e885/switch?back=search
https://app.e-ilustrace.cz/record-detail/ca0b20fc-96d7-42f2-8c7c-3a5ad64a7220/switch?back=search
https://app.e-ilustrace.cz/record-detail/a69cc4bd-ffd1-4627-b9cc-95efac6b7f0b/switch?back=search
https://app.e-ilustrace.cz/record-detail/43f38e29-e9eb-4bed-8641-029ecdf3da39/switch?back=search
https://app.e-ilustrace.cz/record-detail/8b26e00c-9091-4dcd-aaa8-49875105cbdc/switch?back=search

**Comment by VojtechSicha** [comment]
@macholiver A v tuto chvíli poslední dávka 8.

https://app.e-ilustrace.cz/record-detail/db801dd4-deaf-4706-a6ae-48e6357ec17b/switch?back=search
https://app.e-ilustrace.cz/record-detail/8806bd8b-8c11-4d41-b9f2-622a22f9ebc5/switch?back=search
https://app.e-ilustrace.cz/record-detail/182b1d39-bd55-4d1f-8962-4214f16ebc0b/switch?back=search
https://app.e-ilustrace.cz/record-detail/0e830178-4dca-411f-b337-65ff009f8f59/switch?back=search
https://app.e-ilustrace.cz/record-detail/183b55ea-d9d1-46cc-8817-893437f43f4a/switch?back=search
https://app.e-ilustrace.cz/record-detail/c9dbca7d-d6c1-48bf-841b-bbca502319f4/switch?back=search
https://app.e-ilustrace.cz/record-detail/fe76c033-3370-424b-aaa6-d01e7993d1ea/switch?back=search
https://app.e-ilustrace.cz/record-detail/a1e544ae-d70e-472d-9014-22e5d9604b84/switch?back=search

**Comment by macholiver** [comment]
@VojtechSicha Titulné listy dodatočne nahrané

**Comment by VojtechSicha** [comment]
@macholiver skvělé. Nicméně mi jich pár uniklo. Omlouvám se a posílám.

https://app.e-ilustrace.cz/record-detail/612a92fc-e7c9-4a7a-8caa-3722030dfa2c/switch?back=search
https://app.e-ilustrace.cz/record-detail/620698a2-fa66-4b16-a837-a68051cbd546/switch?back=search
https://app.e-ilustrace.cz/record-detail/70d141a3-91c3-4068-a06d-d6b9dcd2bcca/switch?back=search
https://app.e-ilustrace.cz/record-detail/446e3dab-3111-4fdc-8e9d-403f9178d979/switch?back=search
https://app.e-ilustrace.cz/record-detail/8f19233f-d847-407f-a954-73b7f09ec285/switch?back=search
https://app.e-ilustrace.cz/record-detail/347db3a3-7f21-43ff-8541-4af6b2edfbc2/switch?back=search
https://app.e-ilustrace.cz/record-detail/fa3093f5-3f2a-4812-bcc6-563dd52930df/switch?back=search
https://app.e-ilustrace.cz/record-detail/eba38ff9-6b89-43fc-aa73-bf09252c3f83/switch?back=search

**Comment by macholiver** [comment]
@VojtechSicha Ani jeden zo zaznamov neobsahuje pole s titulnym listom. Vsetky 3 zaznamy boli nahrane naposledy 18.1.2024, odvtedy neprisli v dalsej .zip varke XML suborov.
[BCBT32799.txt](https://github.com/LIBCAS/e-ilustrace/files/14784486/BCBT32799.txt)
[BCBT33980.txt](https://github.com/LIBCAS/e-ilustrace/files/14784491/BCBT33980.txt)
[BCBT34008.txt](https://github.com/LIBCAS/e-ilustrace/files/14784492/BCBT34008.txt)
