### ISSUE TITLE
APP - Výstavy mazání

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#126]
@macholiver @Kretiss Na APP mi nefunguje odstranění výstavy. Viz 
![Výstavy mazázní error](https://github.com/LIBCAS/e-ilustrace/assets/127321356/9ef5b3e4-9ec6-44be-87ca-00ffa5cf8da8)

**Comment by Kretiss** [comment]
@VojtechSicha Otestovat na testu ne na produkci
