### ISSUE TITLE
APP - Ztracená vazba kniha-ilustrace 

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#129]
@macholiver Záznamy z BCBT, u kterých se ztratila vazba mezi knihou a ilustrací, ale v EIL jsou.

BCBT35846
Kniha: 
https://app.e-ilustrace.cz/record-detail/b26fbc31-580f-4680-b034-a3e9f6b2d91e/switch?back=search
Ilustrace:
https://app.e-ilustrace.cz/record-detail/5521f608-83a4-4a5f-b3f3-321ec9505bf5/switch?back=search
https://app.e-ilustrace.cz/record-detail/646779f8-0ea6-47c1-8481-c83693250c88/switch?back=search

BCBT34018
Kniha:
https://app.e-ilustrace.cz/record-detail/27795bbf-363a-402d-91df-ee6bef7f1568/switch?back=search
Ilustrace:
https://app.e-ilustrace.cz/record-detail/8b393ea3-4fd7-48f0-aeae-9818662d42db/switch?back=search

BCBT34017
Kniha:
https://app.e-ilustrace.cz/record-detail/941a5f7d-e10a-4c0d-9d29-e9f6d1e20011/switch?back=search
Ilustrace:
https://app.e-ilustrace.cz/record-detail/6494e04f-6619-4aad-896a-8922ba91fb4e/switch?back=search

**Comment by VojtechSicha** [comment]
@macholiver Neprošel záznam knihy K01124 viz https://knihoveda.lib.cas.cz/Record/K01124 Tzn. 123 záznamů ilustrací nemůže být napojeno na záznam knihy.

**Comment by macholiver** [comment]
@VojtechSicha Napojené

**Comment by VojtechSicha** [comment]
@macholiver Narazil jsem na jeden záznam, který si EIL nepřevzala z VuFindu. Byl doplňován teprve nedávno. Jedná se o https://knihoveda.lib.cas.cz/Record/BCBT34014

Záznam ilustrace v EIL přítomný je viz
https://app.e-ilustrace.cz/record-detail/7a54c7f1-f0ea-4e3b-bd4e-305db78c12e4/switch?back=search

**Comment by VojtechSicha** [comment]
@macholiver Ještě jeden případ. Tentokrát z databáze NK. Stejné problém. V EIL chybí záznam knihy viz
https://knihoveda.lib.cas.cz/Record/K00069

Záznamy ilustrací EIL zobrazuje všechny viz např.:
https://app.e-ilustrace.cz/record-detail/5d8d8d12-7ccf-4798-a644-080dd242910f/switch?back=search

**Comment by macholiver** [comment]
@VojtechSicha Zaznam K00069 som nahral: https://app.e-ilustrace.cz/record-detail/c164ef84-71ca-4cd3-8d95-5b34b2e2121d
Pre zaznam BCBT34014 som nedohladal ziadny .xml subor, ktory prisiel v .zip archive, z ktoreho by bolo mozne zaznam nahrat. Pravdepodobne tento zaznam do EIL nikdy neprisiel.

**Comment by VojtechSicha** [comment]
@macholiver Děkuji. Na aktualizaci záznamů z BCBT se doptám kolegy Hejzla. Bude to nejspíš souviset i chybějícími titulními listy v issue #125
