### ISSUE TITLE
Chyby v datech - záznam, který se vůbec nemá objevit

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#13]
O zármutcích velikých církve svaté ...  K18317
Záznam o knize by vůbec neměl projít. Je bez ilustrace. Navíc obsahuje špatná data.
text poznámky se v díle nevyskytuje ; Téma: v záznamu nejsou: Norimberk (Německo), Praha (Česko), Vídeň (Rakousko) ; je zde odkaz na digitalizát díla Naučenie kratke obogi ržečij

**Comment by radenka** [comment]
Za me celkem zahada. TODO @radenka clearnout databazi na TESTu, nahrat data znovu, snad pomuze

**Comment by radenka** [comment]
@VojtechSicha Zaznam s danym identifikatorem neni po nahrati noveho datasetu vubec pritomen
