### ISSUE TITLE
APP - chybné záznamy k odmazání

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#130]
@macholiver Níž je seznam záznamů, u kterých vím, že jsou na zdroji vyřešené a v EIL by se neměly objevovat. Výhledově se to musí pofixovat i ve VuFindu, aby se znovu nenatáhly. Možná by stálo zato testnout to na jednom příkladu, ať se nemusí práce dělat 2x.

https://app.e-ilustrace.cz/record-detail/ce5320a4-7e62-4df9-a927-f25f51ccfc26/switch?back=search
https://app.e-ilustrace.cz/record-detail/89b643c9-0a67-48e5-8f07-9553296470ef/switch?back=search
https://app.e-ilustrace.cz/record-detail/b5e3ec66-8b1e-4396-8e6a-37a346af3cf0/switch?back=search
https://app.e-ilustrace.cz/record-detail/fd8d7165-aaab-4b15-a75f-e90777c8141e/switch?back=search
https://app.e-ilustrace.cz/record-detail/17c6bbb0-12fe-4a23-a81e-30927bf55a1b/switch?back=search
https://app.e-ilustrace.cz/record-detail/a85ab81c-9796-42ed-b1db-c06db5678d00/switch?back=search
https://app.e-ilustrace.cz/record-detail/606cba08-5d29-4aa7-be8f-734189dfd979/switch?back=search
https://app.e-ilustrace.cz/record-detail/4bd0fd85-65f4-4c80-93d5-635773dd65a9/switch?back=search
https://app.e-ilustrace.cz/record-detail/2d046293-3063-4c7c-bb71-646dbc6018da/switch?back=search

**Comment by macholiver** [comment]
@VojtechSicha odmazane
