### ISSUE TITLE
Registrace

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#131]
@macholiver @Kretiss  @StastnyP Při registraci je třeba zakliknout “souhlasím s podmínkami”, jenže podmínky nejsou nijak vydefinované a link nikam nevede. Kam s tím? Textově to připravíme my. Viz
![EIL Podmínky](https://github.com/LIBCAS/e-ilustrace/assets/127321356/d2a7a1d7-988a-4b70-b155-19e8f9a2ef42)

**Comment by Kretiss** [comment]
@VojtechSicha Na tohle se chystala zvlášť stránka, která se zobrazí po kliknutí na ty podmínky. Prozatím je prázdná, takže jak budete mít připraveny podmínky, hodím to tam

**Comment by VojtechSicha** [comment]
@Kretiss Tak textovou část máme viz níže

Česká verze
Podmínky registrace: 
K založení uživatelského účtu je třeba uvést platnou e-mailovou adresu (přijde na ni potvrzovací odkaz) a zadat libovolné heslo (znaky nejsou omezeny). Poskytnutím e-mailové adresy souhlasíte s jejím uložením v databázi. Pro smazání účtu kontaktujte správce databáze přes kontaktní formulář na stránkách e-ilustrace.cz

Anglická verze
Terms of registration: 
To create a user account, you must provide a valid email address (a confirmation link will be sent to it) and enter password (characters are not limited). By providing your email address you agree to store it in the database. To delete your account, contact the database administrator via the contact form on e-ilustrace.cz.

Lze to rozdělit podle cz/aj nastavení app nebo to tam bude jako jeden text? 
Je možné ze sousloví kontaktní formulář (contact form) nebo e-ilustrace.cz odkázat přímo na ten formulář na projektovém webu?

**Comment by StastnyP** [comment]
Vstupní stránky pro Podmínky registrace doplněny ve WP.
@Kretiss prosím nastavit odkazy pro přesměrování.

https://e-ilustrace.cz/podminky-registrace/
https://e-ilustrace.cz/en/terms-of-registration/
