### ISSUE TITLE
Registrace/přihlášení Obnova hesla

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#133]
@macholiver @Kretiss U možnosti zapomenutého hesla nelze do okénka nic zapsat. Je tam připravený BE na odeslanání dalších informací, jak tam slibujeme?
![EIL obnova hesla](https://github.com/LIBCAS/e-ilustrace/assets/127321356/939051b2-01ff-42a6-9299-b7e81e359bd7)

**Comment by Kretiss** [comment]
@VojtechSicha Tady se momentálně nabízí možnost změny hesla jenom pro přihlášeného uživatele, tedy pro toho kdo své heslo zná. Není to zatím nachystané tak jak by to mělo správně být. Z pohledu FE to ale ještě není napojené, to musím dodělat

**Comment by VojtechSicha** [comment]
@Kretiss Rozumím. Ještě tedy chybí možnost - zapomněl jsem heslo, nemůžu se přihlásit, umožněte mi to. Tzn. zadám email a přijde mi výzva k obnově hesla ke stávajícímu účtu. Nechám to tedy otevřené.

**Comment by macholiver** [comment]
@VojtechSicha nasadene

**Comment by VojtechSicha** [comment]
@macholiver Funguje!
