### ISSUE TITLE
APP - záznam k odmazání K14372_IL006*******

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#134]
@macholiver Ještě jsme narazili na jeden dosud opomenutý záznam k odmazání viz https://app.e-ilustrace.cz/record-detail/7187d734-cbe7-4912-88c5-6d5be74318b9

**Comment by macholiver** [comment]
@VojtechSicha predpokladam ze podla nadpisu ma byt odkaz na [tento](https://app.e-ilustrace.cz/record-detail/8a020ffa-3f34-40c3-b286-089378a2e2af) zaznam?

**Comment by VojtechSicha** [comment]
@macholiver ANO. Kolegyně jich vytipovala víc, ale dnes už to nestihnu projít. Budu je sem postupně přidávat.

**Comment by VojtechSicha** [comment]
@macholiver Další várka ke smazání.

https://app.e-ilustrace.cz/record-detail/2e37db08-e1a6-4b91-85a9-0caa7874beb6/switch?back=search
https://app.e-ilustrace.cz/record-detail/30abdc02-0928-44d3-a13a-74bbbb5afa0f/switch?back=search
https://app.e-ilustrace.cz/record-detail/520491d0-f3c3-43ae-87b9-630e5e9574e1/switch?back=search
https://app.e-ilustrace.cz/record-detail/2ef242a6-dbd3-4d14-be93-35d24a9c5227/switch?back=search
https://app.e-ilustrace.cz/record-detail/37e80339-9e46-4bfa-a76a-d74986a02165/switch?back=search
https://app.e-ilustrace.cz/record-detail/ed6d1154-9d95-4977-9d96-30bdcd918754/switch?back=search
https://app.e-ilustrace.cz/record-detail/39be45ad-4fa1-493b-b685-0057c845d36d/switch?back=search
https://app.e-ilustrace.cz/record-detail/f6aa5ad9-c8a5-4ee2-8329-8341adf10bff/switch?back=search
https://app.e-ilustrace.cz/record-detail/89c41e42-a407-4a5d-b4ee-5c88966a8622/switch?back=search
https://app.e-ilustrace.cz/record-detail/d9e4169b-679c-4305-921b-bb36ab91956f/switch?back=search
https://app.e-ilustrace.cz/record-detail/8b8d2dc6-5d4e-4f17-ab74-ff872ff3e0c3/switch?back=search
https://app.e-ilustrace.cz/record-detail/a004a026-82f4-42da-b03d-097d53b44df2/switch?back=search
https://app.e-ilustrace.cz/record-detail/215cec42-e424-4e9f-bef0-e48620f506a9/switch?back=search
https://app.e-ilustrace.cz/record-detail/a87c7444-b0d2-458e-930e-3f03ecf97001/switch?back=search
https://app.e-ilustrace.cz/record-detail/f2bafb0f-5b09-4fba-b323-ed0c50e2f154/switch?back=search
https://app.e-ilustrace.cz/record-detail/c8fc5e21-c6f7-4ac6-bbeb-3ec3bc8dff77/switch?back=search

**Comment by VojtechSicha** [comment]
@macholiver prosím odmazat

https://app.e-ilustrace.cz/record-detail/09b23895-5ad2-42a5-a620-0e889714fc19/switch?back=search
