### ISSUE TITLE
Ladění filtrace

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#137]
- [x] filtrace roky (lišta) - při návratu z detailu záznamu se filtr nezachová
- [x] dynamická reakce facet (tzn. při výběru Kdo, se omezí nabídka v Co a Kdo
- [x] propojit search s facetama
- [x] oddělit vyobrazené osoby
- [x] místo vyhledávacího okna klíčových slov dát facety Kdo (vyobrazené) a Co (vyobrazené)
- [x] přidat klíčová slova do záznamu a do facety Co

**Comment by VojtechSicha** [comment]
@Kretiss Zaškrtnuté (vyřešené) na testu fungují dobře. Akorát ta poslední položka je limitovaná tím, že na testu nejsou klíčová slova. O tom jsme se již dříve bavili. Předpokládám tedy, že je to nastavené tak, že se to projeví až v APP.

Chcete to pustit na produkci takhle částečně nebo budeme čekat, až se podaří vyřešit vše? 

Já bych to rád dal na produkci v tomto stavu a zbytek ladil později. Souhlasíte?

p.s.: mám ještě jeden drobný nedostatek k vyobrazeným osobám. Přidám to sem jako samostatný komentář.

**Comment by VojtechSicha** [comment]
@Kretiss Vyobrazené osoby či instituce (v MARC21 jsou to pole 600 a 610) se týkají pouze záznamů ilustrací. Můžeme se s nimi setkat i v záznamech knih viz obrázek. Tam to ale nejsou vyobrazené osoby/instituce, nýbrž osoby, o kterých dané dílo pojednává. Je to tedy zavádějící. Bylo by možné je pouze zahrnout co kategorie KDO. Tedy u záznamů knih nerozlišovat osoby a instituce na ne/vyobrazené?
![Vyobrazená osoba u knihy](https://github.com/LIBCAS/e-ilustrace/assets/127321356/3b84c9e4-7790-44af-81ae-42dc16ed4d20)

**Comment by VojtechSicha** [comment]
@Kretiss Ještě je potřeba odstranit z faset klíčová slova ze záznamů knih. Nyní se v některých případech nabízí totožné klíčové slovo 2x. Viz obrázek 1. Přičemž ten druhý "pes" nic nevyhledá. A zároveň se tam dostávají matoucí klíčová slova, jako např. časové úseky. Viz obr. 2.

![Klíčová slova](https://github.com/LIBCAS/e-ilustrace/assets/127321356/4143485f-a1ac-4923-bef1-0c37cc05340b)

![Klíčová slova knihy](https://github.com/LIBCAS/e-ilustrace/assets/127321356/cacb8206-2273-4bdf-ab19-c2e0604934b5)

**Comment by VojtechSicha** [comment]
@Kretiss Předpokládám, že testem je míněno to závorkové vyjádření téma. Zde na obr př. moře (téma). To je dobré!

Kolegyni napadlo ještě elegantnější řešení. Pokud by to bylo možné, tak by bylo skvělé dát do závorky místo téma (hlavní motiv) a u klíčových slov (vedlejší motiv). Šlo by to?

![Téma](https://github.com/LIBCAS/e-ilustrace/assets/127321356/aa799e04-7ddb-4ca5-a2e6-a325e311f6ff)

**Comment by macholiver** [comment]
@VojtechSicha "Duplicita" pes je kvoli tomu, ze existuje "Předmětové heslo" pes (Marc 650) aj "Klíčové slovo" pes  (Marc 653). Obe moznosti uz vyhladavaju.
Tie roky napr. 1501-1550 su klucove slova. Konkretne napr. https://app.e-ilustrace.cz/record-detail/44f5dfa1-eab3-4db7-869c-dfcc2b3bc7b0/switch?back=search pre tento zaznam to prislo v Marc 653, ktore je zadefinovane pre klucove slova.
[K16016.txt](https://github.com/LIBCAS/e-ilustrace/files/15220247/K16016.txt)

**Comment by VojtechSicha** [comment]
@macholiver Děkuji. To je skvělé. Snad se ještě kolegovi @Kretiss podaří to rozdělení označením na hlavní a vedlejší motiv, pak už by to bylo dokonalé.

**Comment by macholiver** [comment]
@VojtechSicha nasadene

**Comment by VojtechSicha** [comment]
@macholiver @Kretiss Ano, to je ono!
