### ISSUE TITLE
URGENT obrázy z BCBT v IIIF

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#140]
@macholiver Dobrý den, kolega Hejzl musel reimportovat data z BCBT do VuFindu, protože se nám neaktualizovaly všechny záznamy.

V EIL se to projevilo tím, že je u záznamů ilustrací v náhledu obrázek ilustrace, ale chybí v Miradoru.

Zřejmě se znovu nevytvořily IIIF manifesty. Můžete se na to příležitostně podívat? Viz např.:

https://app.e-ilustrace.cz/record-detail/1fcd0dcf-86d9-4d28-8730-7a8b7fc48c3a/switch?back=search

**Comment by macholiver** [comment]
@VojtechSicha Vyriesene

**Comment by VojtechSicha** [comment]
Skvělé. Děkuji.
