### ISSUE TITLE
VÝSTAV- řazení obrázků - BRÁNÍ V PRÁCI

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#141]
@Kretiss @macholiver V současnosti si řazení obrázků určuje podle neznámého klíče sama aplikace. Zhruba 4. či 5. vložená ilustrace se zařadí libovolně a nelze přesunout na určené místo (resp. v editaci lze přesunout, ale po uložení výstavy se opět zařadí tam, kde byla). Platí to i pro testovací verzi.

**Comment by macholiver** [comment]
@VojtechSicha Poprosim skontrolovat na TESTe.

**Comment by VojtechSicha** [comment]
@macholiver Zatím se mi žádná změna k lepšímu neprojevila. Zkusil jsem vytvořit novou výstavu (zkuste to pod mým přihlášením nebo sám za sebe) Modlitba - test. nahrál jsem šest ilustrací z mého výběru tak, jak mi přišly pod ruku. Chci je mít seřazené INC025_IL117, K17095_030 a K17095_106. V tomto pořadí se mi je podaří seřadit, ale po uložení je jako první K17095_106, ať dělám co dělám.

**Comment by macholiver** [comment]
@VojtechSicha 
Upravené na TESTe. Skontroloval som pri vytvorení, upravení aj zmazaní položky z výstavy.

**Comment by VojtechSicha** [comment]
@macholiver Ano, teď už jsem na žádný problém s řazením nenarazil. Jen ilustrace určená jako Výchozí se výchozí stane až v případě zveřejnění. Ale to už nevidím jako velký problém.

**Comment by macholiver** [comment]
@VojtechSicha Nasadene na PROD

**Comment by VojtechSicha** [comment]
@macholiver Skvělé. Funguje bez problémů.
