### ISSUE TITLE
APP pád - URGENT!

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#142]
@macholiver Kolega Hejzl na konci minulého týdne reindexoval data z NK ČR a nahrál aktuální data na FTP. Nevím, zda je to tím, ale app EIL nejprve v pátek odpoledne nezobrazovala žádná data, pak to bylo v pořádku, následně v sobotu stejný stav a dnes nezobrazuje náhledy ilustrací (v Miradoru po namátkové kontrole jsou). Můžete se na to podívat? Zítra mám prezentaci pro vedení KNAV, takže to docela hoří!

**Comment by macholiver** [comment]
@VojtechSicha prerobili sme fasety, aby neboli tak vypocetne narocne a produkcia nepadala.
Zaroven bolo nutne spustit natiahnutie vsetkych zaznamov, ktore prisli 7.4.2024 v celkovom reindexe od pana Hejzla.
Knihy by mali byt kompletne, aktualne sa natahuju ilustracie. Stav je 376/6000. Ak je to mozne, poprosim o zmiernenie zataze na APP, aby sa zaznamy nahrali co najrychlejsie, bude  to troska dlhsi proces.

**Comment by VojtechSicha** [comment]
@macholiver Děkuji za rychlou reakci. Co si mám představit pod zmírněním zátěže? Prostě teď do app nevstupovat?

**Comment by macholiver** [comment]
@VojtechSicha Vstupovat samozrejme mozete. Predpokladam ze minimalne potrebujete si prejst a nachystat urcite veci. Skor mam na mysli "zbytocnu" aktivitu navyse, ako napr. netestovat teraz fasety, filtraciu, nevkladat vela poloziek do vystav a mojho vyberu a podobne.

**Comment by VojtechSicha** [comment]
@macholiver Děkuji za upřesnění. Než se data natáhnou, nebudeme app zbytečně přetěžovat.
