### ISSUE TITLE
APP DATA

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#143]
@macholiver  Dobrý den, chci se jen zaptat. Data do app se stále natahují nebo se to někde seklo? Př.: https://app.e-ilustrace.cz/record-detail/c2a94f6d-d14f-43b4-af15-acef3f0d6015/switch?back=search

Není k dispozici náhledový obrázek ani obrázky v Miradoru?

**Comment by macholiver** [comment]
@VojtechSicha Dobry den, zaseklo sa stahovanie obrazkov. Zavadu som odstranil, zvysok obrazkov sa stiahol a restartoval som Mirador, aby sa obrazky zaindexovali a naparovali sa ID k zaznamom.

**Comment by VojtechSicha** [comment]
@macholiver Děkuji. Efekt se dostavil. Něco podobného bude asi třeba i u záznamů knih. Nebo stačí počkat?

**Comment by macholiver** [comment]
@VojtechSicha Natiahnutie dát z .xml súborov aj sťahovanie obrázkov prebehlo pre ilustrácie aj pre knihy. Ak je problém s titulnými listami, poprosím Vás o pár príkladov a skontrolujem kde nastala chyba.

**Comment by VojtechSicha** [comment]
@macholiver Jedná o všechny reindexované záznamy z NK ČR. Př.: 
https://app.e-ilustrace.cz/record-detail/714fdb6d-cc45-47c8-8f2c-7d385e76813b/switch?back=search
https://app.e-ilustrace.cz/record-detail/61646120-da81-45e3-a58c-6c33be4466d6/switch?back=search
https://app.e-ilustrace.cz/record-detail/6ff65069-7134-4d00-9e53-d08c14b940b2/switch?back=search

**Comment by macholiver** [comment]
@VojtechSicha 
Ani jeden z týchto záznamov nevyzerá, že by mal titulný list. Dáta sú vytiahnuté z importu 7.4.2024, resp. z dát, ktoré prišli 7.4.2024 a nad ktorými som následne pustil manuálny import.
[K01097.txt](https://github.com/LIBCAS/e-ilustrace/files/14947289/K01097.txt)
[K02257.txt](https://github.com/LIBCAS/e-ilustrace/files/14947290/K02257.txt)
[K17821.txt](https://github.com/LIBCAS/e-ilustrace/files/14947291/K17821.txt)

**Comment by VojtechSicha** [comment]
@macholiver Evidentně je chyba v přenosu ze zdrojové databáze Aleph NK do VuFindu a následně do EIL.

**Comment by VojtechSicha** [comment]
@macholiver Tak mám nedobrou zprávu. Po reindexu VuFindu se do EIL !znovu! dostaly chybné záznamy, které jste už jednou odmazával. Naštěstí je mám poznamenané, takže j znovu naposílám. A není jich tak mnoho. Nicméně na jedné straně řeším s kolegou Hejzlem, že tyto záznamy ve VuFindu nemají co dělat a na straně druhé jsme se bavili o tom, že by si to měla umět ohlídat i EIL. Resp. podle jasně daných parametrů ID by záznamy jako KPS01099_IL090 či K14372_IL006******* vůbec neměly projít.

**Comment by macholiver** [comment]
@VojtechSicha 
Pridana kontrola identifikatora pri importe zaznamov.
