### ISSUE TITLE
APP - chybné záznamy

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#144]
@macholiver Záznamy k odmazání:
https://app.e-ilustrace.cz/record-detail/fc68dfb6-cdc1-4e4f-99fe-6ea67028040d/switch?back=search
https://app.e-ilustrace.cz/record-detail/924bdbb4-5211-42c8-9185-b1fba7c3b4f2/switch?back=search
https://app.e-ilustrace.cz/record-detail/8eb3c3b8-b5e9-401c-a591-924ff33681dd/switch?back=search
https://app.e-ilustrace.cz/record-detail/8ab08edb-375c-415c-b372-027e26b62882/switch?back=search
https://app.e-ilustrace.cz/record-detail/2f51a9fb-2259-44ba-a825-8a642ece738c/switch?back=search
https://app.e-ilustrace.cz/record-detail/ca0227ac-a2e9-467e-b37e-518ce3fd76f6/switch?back=search
https://app.e-ilustrace.cz/record-detail/2d66cddc-2381-4304-9793-c32fa448e2e6/switch?back=search
https://app.e-ilustrace.cz/record-detail/a6c1d158-1761-431b-b0cb-8d2b3b22253a/switch?back=search
https://app.e-ilustrace.cz/record-detail/e222d8f6-e703-445d-8bfa-663698801d84/switch?back=search
https://app.e-ilustrace.cz/record-detail/399defc9-aaf0-42d7-8b46-a4e34a93c74d/switch?back=search
https://app.e-ilustrace.cz/record-detail/2416a232-20a2-498d-a688-7f85ea8bf065/switch?back=search
https://app.e-ilustrace.cz/record-detail/01792aa8-3e97-4032-a696-62624ef5d9f8/switch?back=search
https://app.e-ilustrace.cz/record-detail/77415044-9205-4246-b428-c2ed3e121856/switch?back=search
https://app.e-ilustrace.cz/record-detail/8a14e84c-3e02-4446-8a1d-bbde6c20569f/switch?back=search
https://app.e-ilustrace.cz/record-detail/cfb47934-8178-47bd-bfdb-991b8f7b62ec/switch?back=search
https://app.e-ilustrace.cz/record-detail/a81072f4-4c0e-4261-9a18-c7dafe2715d2/switch?back=search
https://app.e-ilustrace.cz/record-detail/804ec0ed-3771-4eb5-ba46-36e3b3f86219/switch?back=search
https://app.e-ilustrace.cz/record-detail/f0ac7825-dc08-4342-86d7-c6b4174de814/switch?back=search
https://app.e-ilustrace.cz/record-detail/a54e6282-916f-465d-a359-c11e2b0a3915/switch?back=search
https://app.e-ilustrace.cz/record-detail/399837c1-eb0e-485d-9e67-a38d5048db94/switch?back=search
https://app.e-ilustrace.cz/record-detail/804ec0ed-3771-4eb5-ba46-36e3b3f86219/switch?back=search
https://app.e-ilustrace.cz/record-detail/51d8160e-c32b-4821-8ee8-84ddacb5b7e1/switch?back=search
https://app.e-ilustrace.cz/record-detail/69ee9608-e402-4223-9cb0-7307808a18ed/switch?back=search

**Comment by macholiver** [comment]
@VojtechSicha Odmazane

**Comment by VojtechSicha** [comment]
@macholiver Skvělé. Ještě jich pár bude, ale tohle by měla být hlavní dávka.

**Comment by VojtechSicha** [comment]
@macholiver  Děkuji. Posílám nový seznam záznamů k odmazání:

https://app.e-ilustrace.cz/record-detail/2b23b11b-c2f8-4c13-b703-dc931775af4d/switch?back=search
https://app.e-ilustrace.cz/record-detail/e5c51856-550e-4988-9528-6f914f5a3b07/switch?back=search
https://app.e-ilustrace.cz/record-detail/087f784b-35b2-408e-92bf-09f98ef3cf93/switch?back=search
https://app.e-ilustrace.cz/record-detail/dc371c6e-4556-4550-b98c-fd963c45cfc8/switch?back=search
https://app.e-ilustrace.cz/record-detail/a9fa1b06-60bc-4cce-8e5b-832091998441/switch?back=search
https://app.e-ilustrace.cz/record-detail/de6b3812-614f-4a34-b879-21ed84a27087/switch?back=search
https://app.e-ilustrace.cz/record-detail/57b81211-f731-4406-8763-2eb661199047/switch?back=search
https://app.e-ilustrace.cz/record-detail/e5490d6b-c805-471c-8721-f41f189089eb/switch?back=search
https://app.e-ilustrace.cz/record-detail/24db4e23-b784-4480-b8ea-2fcc384de49b/switch?back=search
https://app.e-ilustrace.cz/record-detail/dda46d85-0628-44bc-af18-eb76c4913c44/switch?back=search
https://app.e-ilustrace.cz/record-detail/a55bacf6-d652-43fe-bc94-f2ff82b02019/switch?back=search
https://app.e-ilustrace.cz/record-detail/0e585afb-78e9-4cf4-adf0-845d7780211a/switch?back=search
https://app.e-ilustrace.cz/record-detail/0ab66031-3af7-4ca9-a4e5-eb92eb358492/switch?back=search
https://app.e-ilustrace.cz/record-detail/1452549c-ec70-4608-bd4c-90e41b5b0610/switch?back=search
https://app.e-ilustrace.cz/record-detail/268e6703-8804-416c-b473-04d312da59e2/switch?back=search
https://app.e-ilustrace.cz/record-detail/0ef6658c-060f-4450-ae0e-5465e9201243/switch?back=search
https://app.e-ilustrace.cz/record-detail/268e6703-8804-416c-b473-04d312da59e2/switch?back=search
https://app.e-ilustrace.cz/record-detail/93779051-75b4-4de1-b035-2533e5f35c92/switch?back=search
https://app.e-ilustrace.cz/record-detail/152a624e-88fe-470f-bd0b-21967edb1826/switch?back=search
https://app.e-ilustrace.cz/record-detail/d7230f93-5efd-4af2-95c5-1771e106b709/switch?back=search
https://app.e-ilustrace.cz/record-detail/8d165d9a-0c13-4e28-9a9c-bcd913efe25f/switch?back=search
https://app.e-ilustrace.cz/record-detail/cdcc1f3e-6e45-4be2-846f-7d15c72b5cdd/switch?back=search
