### ISSUE TITLE
DATA k 29.4.

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#145]
@macholiver Kolega Hejzl 28.4. kvůli upgradu reindexoval VuFind a znovu vyexportoval data na ftp EIL. Bohužel mě o tom neinformoval, takže jsem neměl možnost tomu zabránit. Důrazně jsem ho upozornil, že příště takové kroky musí dělat ve shodě a spolupráci s námi, ale to je tak vše, co mi nyní zbylo. 

Bohužel to znamená:

a) dohlédnout na znovu natažení dat a načtení do Miradoru
b) odmazané záznamy znovu vymazat (zde to má alespoň jednu výhodu, že jsme otestovali, zda filtry ID fungují)
c) opětovné doplnění titulních listů

Hluboce se omlouvám!

**Comment by macholiver** [comment]
@VojtechSicha Mirador opraveny

**Comment by VojtechSicha** [comment]
@macholiver Děkuji. Posílám nový seznam záznamů k odmazání:

https://app.e-ilustrace.cz/record-detail/2b23b11b-c2f8-4c13-b703-dc931775af4d/switch?back=search
https://app.e-ilustrace.cz/record-detail/e5c51856-550e-4988-9528-6f914f5a3b07/switch?back=search
https://app.e-ilustrace.cz/record-detail/087f784b-35b2-408e-92bf-09f98ef3cf93/switch?back=search
https://app.e-ilustrace.cz/record-detail/dc371c6e-4556-4550-b98c-fd963c45cfc8/switch?back=search
https://app.e-ilustrace.cz/record-detail/a9fa1b06-60bc-4cce-8e5b-832091998441/switch?back=search
https://app.e-ilustrace.cz/record-detail/de6b3812-614f-4a34-b879-21ed84a27087/switch?back=search
https://app.e-ilustrace.cz/record-detail/57b81211-f731-4406-8763-2eb661199047/switch?back=search
https://app.e-ilustrace.cz/record-detail/e5490d6b-c805-471c-8721-f41f189089eb/switch?back=search
https://app.e-ilustrace.cz/record-detail/24db4e23-b784-4480-b8ea-2fcc384de49b/switch?back=search
https://app.e-ilustrace.cz/record-detail/dda46d85-0628-44bc-af18-eb76c4913c44/switch?back=search
https://app.e-ilustrace.cz/record-detail/a55bacf6-d652-43fe-bc94-f2ff82b02019/switch?back=search
https://app.e-ilustrace.cz/record-detail/0e585afb-78e9-4cf4-adf0-845d7780211a/switch?back=search
https://app.e-ilustrace.cz/record-detail/0ab66031-3af7-4ca9-a4e5-eb92eb358492/switch?back=search
https://app.e-ilustrace.cz/record-detail/1452549c-ec70-4608-bd4c-90e41b5b0610/switch?back=search
https://app.e-ilustrace.cz/record-detail/268e6703-8804-416c-b473-04d312da59e2/switch?back=search
https://app.e-ilustrace.cz/record-detail/0ef6658c-060f-4450-ae0e-5465e9201243/switch?back=search
https://app.e-ilustrace.cz/record-detail/268e6703-8804-416c-b473-04d312da59e2/switch?back=search
https://app.e-ilustrace.cz/record-detail/93779051-75b4-4de1-b035-2533e5f35c92/switch?back=search
https://app.e-ilustrace.cz/record-detail/152a624e-88fe-470f-bd0b-21967edb1826/switch?back=search
https://app.e-ilustrace.cz/record-detail/d7230f93-5efd-4af2-95c5-1771e106b709/switch?back=search
https://app.e-ilustrace.cz/record-detail/8d165d9a-0c13-4e28-9a9c-bcd913efe25f/switch?back=search
https://app.e-ilustrace.cz/record-detail/cdcc1f3e-6e45-4be2-846f-7d15c72b5cdd/switch?back=search

**Comment by VojtechSicha** [comment]
@macholiver Kontrola ve VuFindu (Knihověda.cz) ukázala, že přejímání dat z NK pomocí OAI už funguje, a to včetně titulních listů v poli 856 (vyjádřeno slovy v podpoli y Titulní list). Docela bych se pokusil o finální reimport na ftp. Máte k tomu nějaké výhrady? Bylo by z nějakého důvodu lepší počkat? Já má snad jedinou věc. A sice, že v pátek mám představit EIL návštěvě za zahraničí a nejsem si jist, zda se data natáhnou. Kdyby to tam ale dal kolega dnes, pak by se to mohlo stihnout, co říkáte? Předem děkuji za reakci.

**Comment by VojtechSicha** [comment]
@macholiver Výborně, tak já ho poprosím o import.

**Comment by VojtechSicha** [comment]
@macholiver Dobrý den. Data vypadají po nalití dobře. Bude tam ještě pár drobností, ale nyní prosím o nahození Miradoru a VISE.

**Comment by macholiver** [comment]
@VojtechSicha Mirador aj Vise som restartoval
