### ISSUE TITLE
VÝSTAVY - pořadí

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#146]
@Kretiss Prosím na záložce výstavy přehodit pořadí zobrazení, jak jsme o tom již krátce mluvili. Nejprve Veřejné výstavy a až pod nim Mé výstavy a info o nutnosti přihlášení. Je to detail, ale pro nepřihlášené uživatele je to teď trochu matoucí.

**Comment by VojtechSicha** [comment]
@Kretiss @macholiver Ano může na produkci.

**Comment by macholiver** [comment]
@VojtechSicha nasadene

**Comment by VojtechSicha** [comment]
@macholiver Paráda, tady není co řešit.
