### ISSUE TITLE
Nápověda - nabídka z app

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#147]
@Kretiss Je třeba někam umístit odkaz na nápovědu. Hledáme vhodné umístění.

Přidat na stránku Vyhledávání tlačítko Nápověda (vedle přidat další)  a odkázat na stránku nápověda (otevřít v novém okně).

Z linku na záložce Výstavy Jak využívat nástroj výstavy? odkázat na stránku nápověda (otevřít v novém okně).

https://e-ilustrace.cz/napoveda/
https://e-ilustrace.cz/en/help/

**Comment by VojtechSicha** [comment]
@Kretiss Funkčně je to správně, ale umístění bych si to přestavoval jako na přiloženém obrázku s tím, že by ten černý rámeček mohl být červený.
![EIL nápověda a button](https://github.com/LIBCAS/e-ilustrace/assets/127321356/71e18a91-d9aa-4473-a91a-21f97911f63c)

**Comment by Kretiss** [comment]
@VojtechSicha Pod těmi filtry mi to příjde vhodnější z hlediska responzivního rozlišení -> na menším displeji by to na tom místě dělalo bordel, nehledě na telefonu

**Comment by macholiver** [comment]
@VojtechSicha nasadene

**Comment by VojtechSicha** [comment]
@macholiver Děkuji uzavírám.
