### ISSUE TITLE
DATACE - vyhledávání

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#148]
@Kretiss Filtr podle dat ještě není úplně odladěný.

**Comment by VojtechSicha** [comment]
@Kretiss Bez těch políček mi to přijde v pořádku, ale hází to výsledky mimo vymezený časový rámec. Př. 1541-1555 a mezi výsledky je i záznam ilustrace z roku 1559 https://test.e-ilustrace.cz/record-detail/15e76048-b311-4ae8-87a3-ea1a52c10027/switch?back=search

**Comment by Kretiss** [comment]
@VojtechSicha Zkustě teď

**Comment by macholiver** [comment]
@VojtechSicha nasadene

**Comment by VojtechSicha** [comment]
@macholiver Děkuji. Uzavírám.
