### ISSUE TITLE
Chyby v datech - špatně převedená data v záznamech knih

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#15]
MDLIIII [= 1554] Kozmograffia Cžeská: To gest wypsánij | o položenij Kragin neb Zemij ... K05969 chybně převedená data
témata navíc: Anna Jagellonská,  Norimberk (Německo), Praha (Česko), Vídeň (Rakousko), 

Pocinagy se knizky [!] Kterež slowú Srdečnee Knijžky … K04144
chybně převedená data 
v záznamu se chybně vyskytuje jako autor Luther, Martin, navíc chybná témata: Anna Jagellonská,   Norimberk (Německo), Praha (Česko), Vídeň (Rakousko)

o Mssy Oblasstnij neb Samotnij / a o Pomazanij Kněžskem: Knižka převtěssená… K05115
chybně převedená data 
chybná témata Anna Jagellonská, Norimberk (Německo), Praha (Česko), Vídeň (Rakousko)

Nowý Zákon W Menssijm Miestě Pražském Imprymowany … K17105
chybně převedená data 
v záznamu se chybně vyskytuje jako autor Jan z Příbramě navíc chybná témata: Norimberk (Německo), Praha (Česko), Vídeň (Rakousko), divná poznámka (V roce 1532 tiskl v Plzni pouze Tomáš Bakalář)

**Comment by radenka** [comment]
Data takto pritomna v XML zaznamech, zkontrolovat znovu po nahrani aktualizovaneho datasetu

**Comment by radenka** [comment]
@VojtechSicha Muzete zkontrolovat
- K05969 https://test.e-ilustrace.cz/record-detail/26943adb-ecc9-4eea-bedd-4ef2f01cd919
- K04144 https://test.e-ilustrace.cz/record-detail/a85ff407-a463-472f-a083-d64ae5d54f86
- K05115 https://test.e-ilustrace.cz/record-detail/79bad362-7062-4dec-b231-c646cac11e3a
- K17105 https://test.e-ilustrace.cz/record-detail/005623cb-2448-4ba9-ad6f-b0b4e98e1ab3

**Comment by VojtechSicha** [comment]
@Kretiss pokud pole nemá obsah, není třeba zobrazovat slovní vyjádření . Pak to vypadá, že něco chybí. viz poznámka v zázanmu  K17105 https://test.e-ilustrace.cz/record-detail/005623cb-2448-4ba9-ad6f-b0b4e98e1ab3
