### ISSUE TITLE
Chybějící titulní list

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#150]
@macholiver U tohoto záznamu chybí v EIL titulní list, ačkoli ve VuFindu v datech je. Můžete se na to, prosím, podívat?

https://app.e-ilustrace.cz/record-detail/02a5583a-7572-490d-aaea-30c0e9cb37f8

**Comment by macholiver** [comment]
@VojtechSicha 
Zaznam knihy K02351a nebol spracovany, resp. bol preskoceny pretoze nesplna podmienku ze jeho ID musi koncit na cislicu. Aky je postup v tomto pripade?

**Comment by VojtechSicha** [comment]
@macholiver O této podmínce nevím a nejsem si jist, zda je nutná. Každopádně v případě databáze KPS NK se občas tento typ ID vyskytne (je to způsob pro odlišení variant). Můžeme tu podmínku odstranit?
