### ISSUE TITLE
Vyhledávání Vše ve ID

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#151]
@Kretiss Pokud vyhledávám v ilustracích s roletkou Vše a zadám ID knihy, mělo by mi to vyhodit všechny ilustrace z dané knihy. Zřejmě je tam však nějaké omezení, protože to dá vždy 49 záznamů bez ohledu na to, kolik ilustrací v knize je. Viz příklad na obrázku. Lze to přenastavit?

![Výsledek vyhledávání podle ID](https://github.com/LIBCAS/e-ilustrace/assets/127321356/f410e0f2-a38c-482e-9a7f-fdbe69248b30)

**Comment by VojtechSicha** [comment]
@macholiver Může na produkci.

**Comment by macholiver** [comment]
@VojtechSicha nasadene

**Comment by VojtechSicha** [comment]
@macholiver Děkuji. Uzavírám.
