### ISSUE TITLE
Výstava - počet znaků

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#157]
@Kretiss prosím upravit omezení znaků tak, aby vyšší než povolený počet nebylo možné vložit. Testovací výstava mi umožnila vložit opravdu dlouhý text, který pak (především je to vidět u prezentace v podobě slideru) tzv. přetéká.

Viz obrázky
![Výstava přetékání 3](https://github.com/user-attachments/assets/70480e0e-d1b6-47b1-b65b-c978a21db8b1)
![Výstava přetékání 4](https://github.com/user-attachments/assets/6f66dbac-f0ca-4cfb-a0bc-d60c6f576c09)

**Comment by macholiver** [comment]
@VojtechSicha Nasadené
