### ISSUE TITLE
Přidání do Mého výběru z výsledku rešerše

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#158]
@Kretiss Narazil jsem ještě na jednu drobnost. U výsledku rešerše ve formě soupisu je možnost přidat vybraný záznam do mého výběru. Pokud ale výsledek zobrazím jako galerii, tato ikonka chybí. Lze doplnit? Podobně slouží na záložce ICONCLASS či u Témat.

**Comment by VojtechSicha** [comment]
@macholiver V pořádku. Může na produkci.

**Comment by macholiver** [comment]
@VojtechSicha Nasadené
