### ISSUE TITLE
ALERT! Chybí značná část obrazového materiálu!

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#159]
@macholiver Dobrý den, právě jsem zjistil, že nám v aplikaci chybí velké množství obrázků, a to jak náhledových tak v Miradoru.

Př.: https://app.e-ilustrace.cz/record-detail/590dd49a-8dd9-4194-9f46-0996bbd03e82?back=explore?

tentýž záznam ve VuFindu Knihověda.cz: https://knihoveda.lib.cas.cz/Record/K03171_IL028

**Comment by macholiver** [comment]
@VojtechSicha 
Beží reindex záznamov, nakoľko k dnešnému dňu 9.9. je v prislúchajúcom priečinku obrovské množstvo kníh aj ilustrácií. Vyzerá to, že pán Hejzl spustil celkový reindex. Je nutné počkať až dobehne celkové znovunahranie záznamov.

**Comment by VojtechSicha** [comment]
@macholiver Dobrý den, děkuju za reakci. Je to divné, kolega mi tvrdí, že aktuálně žádný export neprováděl. Ještě to s ním proberu do detailu. Můžete se prosím podívat na průběh exportu? Od rána tam visí cca 200 záznamů s IIIF a dál se to neposouvá. Možná to potřebuje trochu pohnat ;) Předem děkuji. V pátek opět prezentujeme, tak snad se data natáhnou.

**Comment by macholiver** [comment]
@VojtechSicha 
Aktuálne beží už sťahovanie obrázkov. Až dobehne, pustím reindex Mirador a Vise aby sa to premietlo, ale nie je jednoznačné kedy sťahovanie dobehne.
Čo si mám predstaviť od "visí cca 200 záznamů s IIIF"? Chýbajú záznamy? Obrázky? Alebo dáta pre Mirador?

**Comment by VojtechSicha** [comment]
@ Děkuji za informaci. Bylo tím myšleno, že je tam delší dobou stejný počet záznamů s IIIF a vypadalo to, že se nic neděje. Teď tedy čekáme na stažení obrázků Pak mi dejte prosím vědět, až spustíte reindex Miradoru, ať si mohu udělat představu, v jaké jsme fázi. Děkuji a zdravím. VŠ

**Comment by macholiver** [comment]
@VojtechSicha 
To by malo byť spôsobené tým, kedy sa spúšťal posledný reindex Miradoru. Ten nastaví potrebný atribút, od ktorého sa tá IIIF informácia odvíja. Až prebehne Mirador reindex, mala by sa táto informácia aktualizovať.
Budem Vás samozrejme informovať.

**Comment by VojtechSicha** [comment]
@macholiver Děkuji. Mmchd tak přeci jen to jde z části za námi. Kolega reindexoval data zhruba před týdnem, ovšem ne se záměrem pro EIL. Otázkou tedy je, jak tomuto do budoucna zabránit a nastavit tok dat tak, že reindex EIL proběhne jen na naše zadání a reindexy dat do VuFindu, které probíhají určitě častěji než je pro EIL záhodno, by tak na EIL neměly vliv. Možná by stálo za to domluvit si ještě nějaký online meeting, kde si to kolegou doladíte. S pozdravem VŠ

**Comment by macholiver** [comment]
@VojtechSicha 
Prebehol reindex Mirador a Vise.

**Comment by VojtechSicha** [comment]
@macholiver  Dobrý den, už jsem to zaznamenal. Mnohokrát děkuji.  Pokusíme se najít způsob, jak těmto nežádoucím jevům do budoucna zamezit? S pozdravem
VŠ

**Comment by VojtechSicha** [comment]
@macholiver Dobrý den, problém s daty se opakuje!!!

**Comment by macholiver** [comment]
@VojtechSicha 
Opäť rovnaký problém. Na zdieľané FTP bolo nahrané veľké množstvo záznamov (celkový reindex predpokladám). Na prvé rozmyslenie si trúfnem povedať, že je nutné hľadať príčinu/spúšťací mechanizmus u pána Hejzla. Na to zdieľané FTP sa to musí nejakým spôsobom dostať napr. z VuFind a nemyslím si, že EIL si vyberá záznamy a následne si ich na FTP natiahne sám.
EIL sa len pozrie čo bolo do zdieľanej zložky nahrané a až to čo tam objaví nahrá priamo do EIL. Trúfnem si povedať, že InQool neovplyvňuje nahrané súbory v zdieľanom FTP.

**Comment by VojtechSicha** [comment]
@macholiver Proto by bylo dobré se s kolegou spojit. Dříve se reindexovalo též a takovéhle problémy jsme neměli. Kolega mi k tomu zatím napsal jen, že "Je tam jediné pravidlo, teď jsem se díval: pravidelný inkrementální harvest se provádí vždycky pro záznamy importované od půlnoci do poledne následujícího dne. Plný reindex by se tak měl uskutečnit vždycky odpoledne nebo večer." a dodal "No, v tuhle chvíli mě nenapadá, čím bych mohl pomoct, ale když mi hodíš kontakt, tak se s ním spojím."

**Comment by macholiver** [comment]
@VojtechSicha Na strane EIL sa z pohľadu importu taktiež nič nezmenilo. Stále platí, že import sa spustí každý deň pre zložku pomenovanú aktuálnym dátumom a všetky v nej prítomné záznamy sa aktualizujú/vytvoria. Ak k tomu je potrebný meeting tak nie je problém sa spojiť.
