### ISSUE TITLE
Chyby v datech - špatně převedená data v záznamech ilustrací

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#16]
Sloup vázový, nahoře král David     K01463_IL003
chybně převedená data 
neodpovídá obsah poznámkových polí 500

Podobenství o dělnících na vinici (Mt 201-16)    K17102_IL014
chybně převedená data 
chybně autor (Hodějovský z Hodějova, Jan není autorem ilustrace), chybně témata Ježíš Kristus, Norimberk (Německo), Praha (Česko), Vídeň (Rakousko)

Měsíční znamení: Kozoroh    K14372_IL024
chybně převedená data 
ve zdrojové databázi jiná témata, liší astronomie/ astrologická symbolika, chybí Kozoroh (zřejmě ale proběhla změna po předání dat?)

Práce jako důsledek dědičného hříchu    K02357_IL006
chybně převedená data 
jako název použito pole 246 místo 245 správně se ilustrace nazývá Adam obdělává půdu,, chybí dvě poznámky, v tématech v poli 650 chybí „tanec smrti“, chybí literatura

**Comment by radenka** [comment]
@VojtechSicha Muzete zkontrolovat
- K01463_IL003 https://test.e-ilustrace.cz/record-detail/e7bfe881-9d27-4992-8216-6e05323dee51
- K17102_IL014 https://test.e-ilustrace.cz/record-detail/4624bcaf-36f0-43d6-9201-4881f6bd3064
- K14372_IL024 https://test.e-ilustrace.cz/record-detail/7454a00f-0cc5-4a2c-87bf-1d42552ad85c
- K02357_IL006 https://test.e-ilustrace.cz/record-detail/e762e462-35a5-4cbc-9077-51b23d43f1b5

**Comment by VojtechSicha** [comment]
V pořádku
