### ISSUE TITLE
Záznamy k odmazání

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#160]
@macholiver Dobrý den, ještě jsem teď při kontrolách narazil na pár záznamů k odmazání. Předem děkuji a zdravím. VŠ

K1705_IL062
https://app.e-ilustrace.cz/record-detail/36aba6c5-aac9-4829-9499-c33ff8b6d380/switch?back=search

K1705_IL063
https://app.e-ilustrace.cz/record-detail/95e9f91b-a4d1-4254-9161-b93743933632/switch?back=search

K1705_IL064
https://app.e-ilustrace.cz/record-detail/98610d48-0455-4286-acb8-ac63eeb94000/switch?back=search

K1705_IL066
https://app.e-ilustrace.cz/record-detail/7eb1ff9a-1357-4e1a-9cc1-f13658e4138b/switch?back=search

K1705_IL065
https://app.e-ilustrace.cz/record-detail/d152a63b-bb06-4a64-be44-bb5a0653e7d4/switch?back=search

K1705_IL067
https://app.e-ilustrace.cz/record-detail/17224963-19fb-444b-85a8-35cf6b4e1da6/switch?back=search

K0100_IL003
https://app.e-ilustrace.cz/record-detail/8487ef14-cf1f-44b7-9e56-ce674fb3e021/switch?back=search

K0511_IL001
https://app.e-ilustrace.cz/record-detail/410399f1-b4a6-4a16-821f-52df8d81da4e/switch?back=search

K170105_IL068
https://app.e-ilustrace.cz/record-detail/436729cf-5709-4411-a3d5-e1616922eb37/switch?back=search

**Comment by macholiver** [comment]
@VojtechSicha Odmazané

**Comment by VojtechSicha** [comment]
@macholiver Děkuji za nasazení a vyčištění dat. S pozdravem VŠ
