### ISSUE TITLE
Chyba v zobrazení dat - záznam ilustrace

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#18]
Kristus se zjevuje Marii Magdaléně    K17098_IL063
nezobrazují se všechna data

- [x] nezobrazuje se obsah všech poznámkových polí 500, nezobrazuje se autor z pole 100 (kód wdc)
- [x] Ověřit zda jsou správná data na FTP

**Comment by radenka** [comment]
@VojtechSicha Na TEST nahran novy dataset, zaznam je zde: https://test.e-ilustrace.cz/record-detail/6574b925-5e89-46d8-99c6-08c60247a562. Prosim o kontrolu
