### ISSUE TITLE
Řazení pole 260 v záznamu - Nakladatelské údaje

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#19]
Nakladatelské údaje se řadí ve špatné posloupnosti podle podpolí. Nyní je to b, a: c viz 

př.: 
záznam K07008  - Jiří Melantrich z Aventýna starší,Praha : 1564
má být Praha : Jiří Melantrich z Aventýna starší, 1564

- [ ] Nemusíme parsovat, přichází nám v datech s diakritikou, stačí pouze propisovat
- [ ] Zobrazovat samostatně Místo vydání
- [ ] Zobrazovat samostatně Tiskař / Nakladatel

**Comment by Kretiss** [comment]
@radenka Tady máme nějak zaručeno, že všechny tři vyjmenované pole mají stejnou velikost? Musím to vypsat nějakým cyklem, abych to pospojoval. Jestli to zaručit nejde, nemám jak to udělat

**Comment by radenka** [comment]
@Kretiss Myslim ze velikost tech seznamu seznamu `placesOfPublishing` a `originators` v `PublishingEntry` muze byt ruzna... Muzes tam udelat neco jako join pomoci stringu nad tim seznamem? Jsou to oboje seznamy stringu

**Comment by VojtechSicha** [comment]
@Kretiss Většina je správně, ale občas narazím na špatné řazení viz př. K01101

Nakladatelské údaje vypadají takto:
Praha : Bartoloměj Netolický z Netolic : 1549
Jiří Melantrich z Aventýna starší, 1549

Má být:
nakladatelské údaje 
Praha : Bartoloměj Netolický z Netolic : Jiří Melantrich z Aventýna starší, 1549
