### ISSUE TITLE
Filtrace

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/e-ilustrace#2]
- [x] Ve fasetách nabízet seřazenou nabídku abecedně (od A do Z)
- [x] V Kategoriích nabízet seřazenou nabídku abecedně (od A do Z)
- [x] Všude v našeptávačích nabízet seřazené výsledky podle abecedy

Hlavní vyhledávání
- [ ] Vyhledávat v polích - Autor knihy, dílo, název ilsutrace, místo tisku, klíčové slovo, tématické kategorie
- [ ] Kategorie - Autor, tiskař, místo tisku, motiv

https://docs.google.com/document/d/1F1pVQrs-re3TYnlgc8IzQvGJCsK8Zglon1MnyccJSXQ/edit

https://drive.google.com/drive/folders/1B-o2Vo9HB6G6TKe_LBUNYpj6MUgdXH1-

**Comment by Kretiss** [comment]
@StastnyP  Doplnit syntax pro BE filtraci ve smyslu OR

Příklad:
Je potřeba filtrovat podle mainAuthor.id nebo podle subjectPersons.id
Jak ten dotaz zkombinovat tak, aby tomu backend rozumněl?

```
POST record/list
json body: filters: [
{
        field: 'mainAuthor.id',
        operation: 'EQ',
        value: a,
      },
{
        field: 'subjectPersons.id',
        operation: 'EQ',
        value: a,
      }
]

```

**Comment by macholiver** [comment]
Pridal som themes a iconclass do indexu Record.

**Comment by Kretiss** [comment]
@macholiver 

POST author/list

přidat atribut, jestli je osoba z knihy nebo ilustrace, přidat roli (ať se to může na FE podle toho filtrovat)

**Comment by VojtechSicha** [comment]
@macholiver @VojtechSicha @Kretiss Problematika vyhledávání by měla přijít na řadu co nejdříve. Je to propojená záležitost, kterou by bylo dobré společně prodiskutovat. Souvisí také s issue 69.

**Comment by VojtechSicha** [comment]
Zajímavý přípd/příklad Bechyně z Lažan, Jan: na dotaz KDO vyhodí záznam knihy, ve které ale tuto osobu nezobrazujeme, protože je v roli udělovatele povolení k tisku. Záznam ilustrace, na které je erb Jana z Lažan, v jejímž záznamu je bez kódu role, nýbrž v původním poli 600 = zobrazená osoba, pomocí vyhledávací facety nedohledáme.

**Comment by VojtechSicha** [comment]
@Kretiss Mám nějaké výsledky testování vyhledávání ve facetách. Postupně je sem budu přidávat.

**Comment by VojtechSicha** [comment]
@Kretiss 1) na první pohled to vypadá v pořádku, ale nedaří se mi vyhledat (nejsou v nabídce) některé konkrétní umělce př. MS, EWA, ME. Zároveň by mělo dojít k drobné úpravě v inormačním textu v okénku. nyní je tam Vyhledej autora, což by se tedy mělo změnit na Vyhledej osobu

**Comment by VojtechSicha** [comment]
@Kretiss myslím, že to bude chtít ještě jednu interní online poradu ;)

**Comment by VojtechSicha** [comment]
@macholiver Filtrování může na produkci, ale ještě bych s kolegou něco chtěl probrat. Každopádně takhle už to dává smysl.

**Comment by VojtechSicha** [comment]
Diskuze proběhla. čeká se na realizaci.
