### ISSUE TITLE
Záznam knihy - Informace o počtu souvisejících ilustrací

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#21]
U záznamu knihy ve výsledku rešerše by měl být umístěn počet ilustrací viz př. níže

K03104
Postylla cžeska [!] Totiž / Kázanij na Euangeliá … GIT
[Hoffmeister, Johannes, 1509-1547](https://knihoveda.lib.cas.cz/Search/Results?lookfor=Hoffmeister,%20Johannes,%201509-1547&type=Author)
Prostějov : Jan Günther, 1551

						                                      Počet ilustrací: 103

- [x] Na BE fetchnout souvisejici ilustrace
- [ ] Zobrazovat na FE počet ilustrací

Pro dalsi info viz https://drive.google.com/drive/u/0/folders/1B-o2Vo9HB6G6TKe_LBUNYpj6MUgdXH1-

**Comment by radenka** [comment]
@VojtechSicha Prosim, tim "vysledkem reserse" myslite stranku detailu zaznamu? Nebo chcete ten pocet ilustraci zobrazovat i na te strance "Vyhledavat"?

**Comment by VojtechSicha** [comment]
@radenka Výsledkem rešerše myslím seznam vyhledaných knih na stránce vyhledávat. Tedy před tím než uživatel vstoupí do záznamu. V samotném záznamu už uživatel uvidí ilustrace v Miradoru.

**Comment by radenka** [comment]
@Kretiss Seznam ilustraci jsem tedy dala jak do DTO pro `/detail`, tak `/list` (v detailu pravdepodobne casem pribude i odkaz/idcko na konkretni soubory)
