### ISSUE TITLE
Chyby v datech - záznamy bez obrazového dokumentu

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#23]
Záznam bez obrázku není nelze rozkliknout/otevřít.

https://test.e-ilustrace.cz/record-detail/00f98960-6154-4e8e-805f-90e9b787c38c

**Comment by StastnyP** [comment]
Potřeba dodat updatovaný soubor dat.

**Comment by radenka** [comment]
@VojtechSicha Odkaz v zadani jiz nefunguje, protoze entita byla nalitim novych dat smazana. V soucasnosti se detaily zaznamu bez importovanych obrazku v pohode zobrazuji.
