### ISSUE TITLE
Vizuál záznamů 

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#24]
Obsah některých polí se nyní  v záznamech dubluje (př.: ID a odkaz na Knihovědu, název), některé položky jsou/budou navíc ( př. odkaz na Ilustraci a stranu s ilustrací). 

- [x] Název stačí jednou (v nadpisu), odebrat atribut Název

- [x] Číslo záznamu provázat s odkazem na knihovědu a odkaz zrušit

- [ ] Zrušit odkazy Ilustrace/Strana s ilustrací - ořez bude v náhledu a pak i scelou stranou v Miradoru

- [x] U ilustrace chybí proklik na záznam celého díla. "Ilustrace v:" ID knihy s odkazem na knihu
  - [x] propisovat z BE číslo záznamu Knihy

**Comment by VojtechSicha** [comment]
@Kretiss V takovém případě se přikláníme k ponechání názvu, tak jak to je. Tzn. s opakováním.

**Comment by Kretiss** [comment]
@VojtechSicha @radenka Nachazí se v jsonu z BE pod klíčem `links` i jinačí odkazy než tyto dva zmíněné? Jestli ne, tak to prostě skryjem, jestli jo, bude potřeba to nějak filtrovat, ať už na FE nebo na BE.

**Comment by VojtechSicha** [comment]
@Kretiss 
Linky jsou dvojího druhu u knih i ilustrací, ponechat jako součást záznamu chceme vlastně pouze jeden.

Knihy
Digitální kopie
Titulní list

Odkaz na digitální kopie daných tisků musí zůstat součástí záznamů (tedy ponechat)
Odkaz na titulní list nepotřebujeme. Stačí když se obrázek titulního listu zobrazí v záznamu a u jeho zkrácené podoby ve výsledku rešerše.

Ilustrace:
Ilustrace
Strana s ilustrací

Oba by měly zmizet ze záznamu, neboť obrázky budou součástí záznamu ale  v nástroji Mirador.
