### ISSUE TITLE
Nezobrazuje se obsah pole 300

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#25]
To znamená pole 300 určené pro rozsah. Podpole má a b c. Převážně ale jen a c.

Údaje o stránkování knihy.

Údaje rozměrech ilustrace.

**Comment by radenka** [comment]
@Kretiss prosim overit, ze se u Recordu zobrazuje obsah atributu `physicalDescription`, `technique` a `dimensions`. Atributy muzou byt null. Vyplnene (not null) jsou napr. u recordu `4fca4ca1-b55b-402f-b6ab-0441629721dc`, K17102_IL078.

**Comment by Kretiss** [comment]
@VojtechSicha Prosím o specifikaci kde a jak to má být zobrazené
