### ISSUE TITLE
Pole 264 Ilustrace

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#26]
U ilustrace se může stát, že má pole 264 vyplněné 2x

Př.: K01005_IL021

1) Nakladatelské údaje: Olomouc : Jan Günther, 1557     (pole 264)

2) Údaje o štočku: [Norimberk] : [Mistr z Schönova okruhu], [1546]   (pole 264 3)

Druhé uvedené se nyní nezobrazuje.

**Comment by radenka** [comment]
@Kretiss Udaje o stocku jsou v `Record#printingPlateEntry`, atribut neni povinny (muze byt null). Zobrazit na FE.

**Comment by VojtechSicha** [comment]
@Kretiss  zde by to ještě chtělo dotáhnout to slovní vyjádření.

Zatím to vypadá takto viz K17597_IL064:

Nakladatelské údaje  Praha : Jan Kosořský z Kosoře, 1553
                                  [Praha?] : [MC], 1552

Mělo by být:

Nakladatelské údaje  Praha : Jan Kosořský z Kosoře, 1553
Údaje o štočku          [Praha?] : [MC], 1552

**Comment by VojtechSicha** [comment]
@Kretiss  tady jen detail.

Nyní se to zobrazuje takto:

**Nakladatelské údaje**  Praha : Pavel Severýn z Kapí Hory, 1537
                                        Údaje o štočku [Wittenberg] : [MS], [1534]

Správně by to ale mělo být:

**Nakladatelské údaje**  Praha : Pavel Severýn z Kapí Hory, 1537
**Údaje o štočku**          [Wittenberg] : [MS], [1534]

**Comment by VojtechSicha** [comment]
@Kretiss Většina je správně, ale občas narazím na špatné řazení viz K17597_IL042

Údaje o štočku [Praha?] :, [1552] [MC],

Má být:
Údaje o štočku [Praha?] : [MC], [1552]

**Comment by VojtechSicha** [comment]
@VojtechSicha K17597_IL042 chyba v KPS podpole c je zapsáno jako podpole a.
