### ISSUE TITLE
Literatura pole 510

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#27]
U pole 510 se nezobrazuje podpole c, tzn. stránkování citovaných zdrojů. Také by bylo vhodné jednotlivé citace oddělit. Stačí na vždy při opakování pole 510 začínat novým řádkem.

př. K01005_IL021 

Voit;2017: Voit, P.: Český knihtisk mezi pozdní gotikou a renesancí. Tiskaři pro víru i tiskaři pro obrození národa 1498-1547. Praha 2017,, Brtová;1950: Brtová, B.: Moravský knihtiskař Jan Günther. Disertační práce na katedře knihovnictví FF UK. Praha [1950], nepublikováno. 

Má být :

Voit;2017: Voit, P.: Český knihtisk mezi pozdní gotikou a renesancí. Tiskaři pro víru i tiskaři pro obrození národa 1498-1547. Praha 2017, str. 619-620; str. 664-666, č. 66
Brtová;1950: Brtová, B.: Moravský knihtiskař Jan Günther. Disertační práce na katedře knihovnictví FF UK. Praha [1950], nepublikováno.

**Comment by radenka** [comment]
Seznam `references` v `Record` obsahuje instance  tridy `Reference`, Je potreba zobrazovat jeho atribut `location` (tam jsou u knih ty cisla stran)
