### ISSUE TITLE
ICONCLASS - kódy

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#31]
@VSladka 

Do IC tvořit dotaz na údaje před závorkou, obsah závorky pouze v případě, že se v IC nachází, následně údaje za závorkou.

V záznamu zobrazit tak, jak je kód uveden v tabulce celkové evidence a doplnit o slovní vyjádření z IC..

**Comment by VSladka** [comment]
Příklad v tabulce Celková evidence: 61B2(BEDŘICH)11
do ICONCLASSu dotaz v této formě 61B2(...)11
"Bedřich" v IC není

Příklad v tabulce Celková evidence: 11HH(BARBARA)
do ICONCLASSu dotaz ve formě 11HH(BARBARA)

**Comment by VSladka** [comment]
obecně strukturu ICONCLASS kódu tvoří: dvě číslice, poté písmeno (případně zdvojené písmeno), dále mohou následovat v zápise až 3 číslice a nakonec závorka, v níž je znaménko pro sčítání (+) a číslice
zápis ICONCLASS kódu může sestávat ze dvou závorek (první pro zápis vlastního jména, konkrétní lokality, druhu apod.; do druhé se číslicí a znaménkem plus vepisují tzv. klíče zpřesňující informace): 
např. 61B2(...)13(+3)

**Comment by radenka** [comment]
@VSladka 
1) Ohledne existence zavorek, muzou nastat obe nasledujici varianty (cislice a pismena si vymyslim)? Tedy ze zavorka, kterou iconclassovy kod konci, nemusi (ale muze) byt ona zavorka "s Bedřichem" :) ?
- 61B2(...)
- 61B213(+3)

2) Muze se stat, ze zavorka s pluskem a cislici  se vyskytne i uprostred iconclassoveho oznaceni? Napr. 61B2(+3)123?

**Comment by VSladka** [comment]
1. ano mohou; může nastat tento případ: 25F32(...)(+1) anebo 25F32(BIRD)(+1)
2. závorka s plusem může být jen na konci záznamu

**Comment by radenka** [comment]
Generalizace iconclassovych kodu typu 61B2(BEDŘICH)11 na variantu 61B2(...)11 nakonec neni vyzadovana, do EIL se uklada kod 61B2(BEDŘICH)11 s odkazem do Iconclassu smerujici primo na tento konkretni koncept.
