### ISSUE TITLE
Chyby zaznamu - pole 001 neobsahuje podtrzitko

### ISSUE THREAD

**Issue by radenka** [LIBCAS/e-ilustrace#37]
@VojtechSicha 
Ma za nasledek chybne vyhonoceni zaznamu -> je povazovan za knihu, ikdyz se jedna o ilustraci. 
Jestli je to mozne, prosim o opraveni ve zdrojovych databazich a zaslani v aktualizovanem datasetu.

Zaznamy (~ obsah pole 001):
- K05840 IL016
- K05111 IL002

**Comment by VojtechSicha** [comment]
@radenka v obou případech jsou data ve zdrojové databázi KPS i v knihovědě v pořádku. Chyba bude někde v přenosu dat

**Comment by radenka** [comment]
@VojtechSicha Oba z techto zaznamu se k nam dostavaji duplikovane - v importovanem ZIPku jsem nasla soubory `K05840_IL016.xml`, `K05840 IL016.xml`, `K05111_IL002.xml` a `K05111 IL002.xml`. Soubory obsahujici podtrzitko jsou spravne identifikovany jako ilustrace, jejich "bezpodtrzitkove" varianty pak jako knihy. Obsah je temer totozny, az na par radku... Kazdopadne mi to prijde jako zbytecna duplicita, navic zpusobujici chyby. Zkusite prosim kontaktovat pana HH, jestli by nedokazal tyto duplicity odfiltrovat?

**Comment by VojtechSicha** [comment]
Přeposláno J.H.

**Comment by welblaud** [comment]
@radenka Díky za hlášení, ideální by bylo asi záznamy s mezerou prostě na vstupu ignorovat. Díval jsem se, našel jsem jich asi 5, které jsem hned smazal i u nás. Pokusím se to upravit už na vstupu k nám, ať se to nedostane ani do Solru 🙂
