### ISSUE TITLE
Ilustrace z BCBT

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#39]
@radenka Včera jsem upravil obsah pole 856y u ilustrací z databáze BCBT (KNAV), po dnešní aktualizaci se to již projevilo ve VUFindu knihoveda.cz. Předpokládám, že tuto aktualizaci přijme E-ilustrace během své večerní aktualizace, tudíž by se měly ilustrace (myšleno obrázky, záznamy jsou již přítomné) zítra objevit v E-ilustraci. Pokud se mýlím a měly se tam promítnout již dnes, tak poprosím o kontrolu toku dat.

**Comment by radenka** [comment]
@VojtechSicha Updatovani zaznamu mam v TODO listu, ale zpracovano jeste neni. Ilustrace se tedy neaktualizuji, leda bych rucne promazala existujici zaznamy a nahrala je znovu. Nyni jsem se zamerila na integrace s Iconclassem a anotovani zaznamu.

**Comment by VojtechSicha** [comment]
@radenka Dobře, nechávám issue otevřené s tím, že jsou u nás data připravená a po updatovani je zkontrolujeme.
