### ISSUE TITLE
Seznam souvisejících ilustrací ze stejné knihy v záznamu ilustrace

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#42]
@Kretiss  Součástí záznamu ilustrace by měl být i seznam ostatních ilustrací ve stejné knize. Ideálně formou ID Název jako aktivní link směřující na vybranou související ilustraci.

**Comment by Kretiss** [comment]
@VojtechSicha Data nachystané máme, teď je ale otázka, jak to rozumně zobrazit. Např u https://test.e-ilustrace.cz/record-detail/a5b7fbfe-a048-4cd3-92b9-c7569c9107ad se mi vrátilo pole o 150 souvisejících ilustracích a to tam zobrazit nemůžeme, protože by to bylo strašně dlouhé

**Comment by VojtechSicha** [comment]
v řešení 17.10.23
