### ISSUE TITLE
IC strom

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#45]
@VSladka @radenka překlady IC do češtiny

**Comment by Veronikasladka** [comment]
v tomto [Google dokumentu](https://docs.google.com/document/d/19-8p1zdUZ_wZmtyDIQYbxNQ9EUBNQb4IeJBYHzY4JPY/edit?usp=sharing) je přeložený strom ICONCLASS (první a druhá úroveň)

**Comment by radenka** [comment]
@Veronikasladka Prosim o zpristupneni dokumentu, nyni se do nej nedostanu, posilala jsem zadost pod e-mailem slana@inqool.cz. Dekuji

**Comment by macholiver** [comment]
@Veronikasladka Taktiez poprosim o pristup do dokumentu. Ziadost poslana pod e-mailom oliver.mach@inqool.cz. Dakujem
