### ISSUE TITLE
TÉMATA: Kategorie a klíčová slova

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#46]
popsat přesně, co a jak se má na záložce TÉMATA odehrávat.

**Comment by VojtechSicha** [comment]
@radenka @Kretiss 

Záložka TÉMATA má být především vizuální, takže bude mít pouze formu galerie a má umožnit uživateli:

- vyhledávat v předem definovaných kategoriích
- vyhledávat pomocí klíčových slov
- upřesňovat dotazy pomocí jednoduchého filtru

Funkčně by to mělo vypadat následovně:

- po výběru tematické kategorie/dlaždice) dostane uživatel výsledek rešerše v podobě galerie ilustrací z dané kategorie
- seznam klíčových slov se přizpůsobí obsahu v záznamech ilustrací. Tzn. pokud v dané kategorii nebude záznam s klíčovým slovem "pes", pak se toto klíčové slovo v nabídce nebude vyskytovat. Zároveň by bylo dobré, aby za klíčovým slovem byl počet výskytů ve vyfiltrované množině
- při výběru klíčového slova/klíčových slov dostane uživatel výsledek rešerše v podobě galerie ilustrací, jejichž záznamy příslušná klíčová slova obsahují

POZOR! do kategorie klíčových slov v tomto případě zahrnujeme všechna pole 6XX

**Comment by radenka** [comment]
Klicova slova - relevantni pole:
600: osoba jako predmet dila
610: instituce jako predmet dila
650: predmetove heslo
651: misto jako predmet dila
653: klicova slova (aktualne pouze String)
655: zanr/forma

**Comment by VojtechSicha** [comment]
@Kretiss Toto téma bude zřejmě potřeba znovu probrat s novým kolegou na BE

**Comment by Kretiss** [comment]
@macholiver Přidat počty k jednotlivým tématům 

<img width="286" alt="obrazek" src="https://github.com/LIBCAS/e-ilustrace/assets/74928322/8e12ec82-92a5-401e-9d8a-f9e7dc36e433">

**Comment by macholiver** [comment]
@Kretiss ```GET /theme/count``` vrati pole ThemeCount

**Comment by VojtechSicha** [comment]
@Kretiss  Na první dobrou je to lepší než samá 0, ale mělo by to také reagovat na další zúžení dotazu.

Př.: Erby 258, zúžím dotaz pomocí hesla "rodové znaky ", takže mám 98 záznamů, ale u Erbů vlevo je stále 258

**Comment by Kretiss** [comment]
@macholiver https://github.com/LIBCAS/e-ilustrace/issues/46#issuecomment-1576395137 můžeme na to udělat endpoint?

**Comment by macholiver** [comment]
@Kretiss 
600: osoba jako predmet dila -> POST /subject/person/list
610: instituce jako predmet dila -> POST /subject/institution/list
650: predmetove heslo -> POST /subject/entry/list
651: misto jako predmet dila -> POST /subject/place/list
653: klicova slova (aktualne pouze String) -> TODO
655: zanr/forma -> POST /genre/list

**Comment by Kretiss** [comment]
Dropdown

**Comment by VojtechSicha** [comment]
@Kretiss Po uvážení bych zde nechal jen to okénko CO. Kde nemá takový význam, jak jsem si myslel ;) Zároveň by tam to slovní vyjádření Co ani nemuselo být. vyhledávací okno logicky navazuje pod nadpisem klíčová slova. šlo by to takto?

**Comment by VojtechSicha** [comment]
@Kretiss Pardon, ještě jinak. Mělo by tam být Kdo a Co - abychom mohli snáze třídit podle vyobrazeného.

**Comment by VojtechSicha** [comment]
@Kretiss Říkal mi kolega Šťastný, že jste měli ještě interní diskuzi ohledně faset v záložce Témata a že vám přijde (s ohledem na uživatele) nejlepší je přidat ve stejné podobě jako jsou na záložce Vyhledávání.

Tak jsme to u nás také interně probrali ;)

Došli jsme ale k závěru, že bude opravdu nejlepší, když budou k dispozici jen dvě okénka:

KDO - vyobrazené osoby

CO - vyobrazená témata (hlavní motiv) a klíčová slova (vedlejší motiv)

Je to vyhledávání tematické, další údaje si uživatel obstará jinde.

**Comment by VojtechSicha** [comment]
@macholiver Může na produkci.

**Comment by macholiver** [comment]
@VojtechSicha nasadene

**Comment by VojtechSicha** [comment]
@Kretiss @macholiver Funguje a je to velmi nápomocné. Děkuju!
