### ISSUE TITLE
Migrace obohacených dat z excelu

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/e-ilustrace#47]
- [ ] Z excelu propisovat inconclassové hesla + témata (sloupčky E, S, F)
- [x] Evidovat stav iconclassu v administraci
- [x] Stav u témat není potřeba, jen v administraci umožnit filtrování, kde je téma u záznamu vyplněno / nevyplněno.

**Comment by radenka** [comment]
@StastnyP Prosim presneji vydefinovat, co znamena "editovat stav Iconclassu v administraci" - mame preddefinovanou mnozinu techto stavu?

**Comment by StastnyP** [comment]
@radenka stavy podle excelu, jsou tam "In progress" + "Done" + bych přidal neobohacneo "Unenriched"

**Comment by Kretiss** [comment]
<img width="677" alt="obrazek" src="https://github.com/LIBCAS/e-ilustrace/assets/74928322/7d2c2e18-1849-41b6-8cfb-d626441aec54">


Budou dva stavy, jeden pro iconclass, jeden pro témata. Půjde si vybrat stav, který se uloží v db a zobrazí se na FE
