### ISSUE TITLE
Updatovani zaznamu - relevantni atributy v zaznamu knihy/ilustrace

### ISSUE THREAD

**Issue by radenka** [LIBCAS/e-ilustrace#49]
@VojtechSicha Prosim o zodpovezeni otazek/diskuzi k tematu aktualizace zaznamu v EIL (aktualizaci myslim znovu-importovani kompletniho XML zaznamu). Nastinim na poli 100:

**Predpoklad:** Autor, ktery je v XML specifikovan v poli 100, jiz v EIL existuje.
**Resena situace:** Daneho autora nechceme z DB vymazat a nahrat ho nanovo, ale updatovat jeho atributy na zaklade informaci z prave zpraocovavaneho XML.

**Dotazy:**
1.  Na zaklade ktere mnoziny atributu autora je vhodne testovat, ze autor jiz v DB existuje? Pouze na zaklade jmena (podpole `'a'`) mi to prijde malo - v DB test.e-ilustrace vidim napr. autora se jmenem pouze "Ferdinand" a tech pravdepodobne muze byt vice. Delat tedy kontrolu existence na zaklade jmena (podpole `'a'`) , cislovani (podpole `'b'`) a doplnku ke jmenu (podpole `'c'`) zaroven?
1.1 **Doplnujici dotaz** - Ma pro vas smysl ukladat u autora jmeno, cislovani a doplnek ke jmenu samostatne?  Potrebujete nekdy filtrovat autory pouze jmena nebo podle doplnku? Aktualne zminene atributy ukladam oddelene - coz umoznuje prave zminene "oddelene" zpusoby filtrovani.

2. Kdyz je v poli 100 definovan autor, ktery uz v EIL existuje, ma probehnout update uplne vsech dat, ktera se autora tykaji? (jmeno, cislovani, doplnek, datum narozeni atd.) nebo jde jen o nejakou podmnozinu (napr. pouze autoritni kod?). Z meho pohledu by se jmeno, cislovani a doplnek vlastne menit nemel (proto navrhuji kontrolu existence autora v EIL na zaklade techto tri atributu, protoze jsou podle me nemenne). 
Dotaz se vaze zaroven k polim, ktera popisuji nejakou osobu - osoba jako predmet dila (pole 600) a puvodce (pole 700).

3. Rozsireni predchozi otazky i na ostatni entity v EIL: Jake atributy ma EIL pri updatovani brat v potaz pri entitach:
- instituce jako autor (pole 110), instituce jako predmet dila (pole 610), instituce jako puvodce (pole 710)
- predmetove heslo (pole 650)
- misto jako predmet dila (pole 651)
- zanr (pole 655)
- misto vydani (pole 984)
(Mne se zda, ze vzdy pujde o aktualizaci pouze autoritniho kodu, ale prosim o vyjadreni)

4. V kontextu poli zminenych v predchozich dotazech, ktera jsou zaroven opakovatelna: Mam predpokladat situaci, kdy je ze zaznamu  napr. ze seznamu puvodcu (pole 700 nebo 710) nejaky puvodce odebran? Stavaji se tato "zuzeni", tedy je potreba je zpracovat a korektne promitnout do EIL?

U ostatnich poli krome zminenych vyse v dotazech mohu (a planuji) aplikovat plne cisteni - tedy ze data ze zaznamu uplne vymazu a znova je tam nahraji z prave zpracovavaneho XML (netyka se obrazku - na to pripadne zalozim separatni issue).

**Comment by VojtechSicha** [comment]
@radenka navrhuji samostatnou online schůzku. Zítra nebo v pondělí?
Ale pokud dáváte přednost psané formě, postupně to sem vypíšu.

**Comment by radenka** [comment]
@VojtechSicha Urcite muzeme dnes, muzu kdykoliv behem dne. Pardon za nereagovani, mela jsem od ctvrtka volno.

**Comment by radenka** [comment]
1. existenci kontrolovat na zaklade atributu: jmeno, cislo, doplnek ke jmenu
- pozn. je potreba zajistit synchronizaci jmen z databaze autorit -> HH
- pokud Author ma jen jmeno a ne cislovani ani doplnek, pak existenci entity kontrolovat i na zaklade zivotnich dat
- 1.1 mozno sjednotit do jednoho atributu jmeno+cislovani+doplnek

2. atributy, nad kterymi probiha update v entite Author (podobne SubjectPerson, kolekce `authors` v Recordu)
- birthYear, deathYear, autoritni kod

3. atributy k updatu v entitach:
- instituce jako autor (pole 110), instituce jako predmet dila (pole 610), instituce jako puvodce (pole 710)
- predmetove heslo (pole 650)
- misto jako predmet dila (pole 651)
- zanr (pole 655): vsude updatovat jen autoritni kod
- misto vydani (pole 984): + jeste `country`

4. Jj, mazani se muze stat - zapracovat

**Comment by VojtechSicha** [comment]
Výše je shrnut výsledek diskuze během schůzky. Předávám zpět na BE.
