### ISSUE TITLE
Filtrace – FE

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/e-ilustrace#54]
- [ ] Rok – nabízet roky (od, do) podle data v ilustracích – dodělat k tomu endpoint
- [ ] Pokud je vybrán rok, propisovat jej do tabulky pro zrušení filtru

**Comment by VojtechSicha** [comment]
Zde budeme uvádět nedostatky, které vyplynou z testování.

**Comment by Kretiss** [comment]
Doplnit endpoint na rozsah yearFrom a yearTo pro search. Zrušit slider a dát tam přímo inputy na psaní
