### ISSUE TITLE
Entita žánr

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#60]
Neprochází data pro žánry. FE nastaveno, aby se obsah zobrazoval, ten ale chybí.

**Comment by macholiver** [comment]
Fix zlej konštanty tagu pre DataFieldMapper655.

**Comment by macholiver** [comment]
@VojtechSicha prosím skontrolovať či sa správne nahrávajú Žánry.
https://test.e-ilustrace.cz/record-detail/061fffbe-44d0-4ef7-a573-fa0a9ac962f0/switch
https://test.e-ilustrace.cz/record-detail/ef296aac-d2da-46c1-96a8-89da7467e430/switch
https://test.e-ilustrace.cz/record-detail/8a40091f-2fcc-4612-be30-e25cf803f63c/switch

**Comment by VojtechSicha** [comment]
@macholiver  U příkladových záznamů ANO.
