### ISSUE TITLE
Zkontrolovat, proč se duplikují záznamy v poli links

### ISSUE THREAD

**Issue by Kretiss** [LIBCAS/e-ilustrace#61]
<img width="489" alt="obrazek" src="https://github.com/LIBCAS/e-ilustrace/assets/74928322/c0915822-6d81-4751-8066-788141af20eb">

<img width="562" alt="obrazek" src="https://github.com/LIBCAS/e-ilustrace/assets/74928322/64150f6b-4dc0-4b5b-bbea-8ec2ebada1b3">

**Comment by VojtechSicha** [comment]
Další př. 
BCBT37034_IL001

**Comment by macholiver** [comment]
Pridaná kontrola URL adries pri pridávaní nových záznamov do links.
