### ISSUE TITLE
BCBT42624 - chybné odkazy

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#66]
@macholiver  Správně se má zobrazovat pouze link na digitalizát v NK. Odkazy na skeny kartotečních karet nejsou žádoucí. Řešeno již v počátcích s R. Slanou. Příležitostně vysvětlím podrobnosti.

**Comment by macholiver** [comment]
Nestahovat a nezobrazovat pole Obalka (856).
Ziaduce (najma) zaznamy s oznacenim "4".

**Comment by macholiver** [comment]
BCBT záznamy obsahujú polia pre obrázky ilustrácie a stranu s ilustráciou bez označenia 4. Nakoľko bolo požadované, aby sa spracovávali len polia 856 s označením 4, upravila sa podmienka, aby sa záznamy bez označenia 4 spracovali v prípade, že sú určené pre obrázky ilustrácií alebo kníh. Ostatné polia 856 bez označenia 4 sú ignorované.
