### ISSUE TITLE
Příkladové záznamy ke smazání a následné aktualizaci a testu změn

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#70]

**Comment by VojtechSicha** [comment]
@macholiver 

K01098 - všechny ilustrace připojené k této knize nemají v EIL obrázky (cca 300 položek). Příkladově můžeme odebrat a znovu natáhnout K01098 _IL001 až K01098 _IL005

BCBT37390 - podobně jako výše tzn. odstranit  a znovu nahrát BCBT37390 _IL001 až BCBT37390_IL005

U těchto dvou knih chybí  v EIL záznam BCBT37252 a BCBT37255 takže i související ilustrace
BCBT37252_IL001 BCBT37252_IL002 BCBT37255_IL001 (tady by bylo dobré zjistit, proč záznamy o knihách neprošly)

Dále dva příklady chyby, která již byla na zdroji odstraněna K01711_004  a K05111 IL002, ale v EIL stále visí. V první případě jako ilustrace v druhém dokonce jako záznam knihy

**Comment by macholiver** [comment]
```
________________
Nahrať znovu
________________
BCBT37390_IL001
BCBT37390_IL002
BCBT37390_IL003
BCBT37390_IL004
BCBT37390_IL005

K01098_IL005
K01098_IL006
K01098_IL007
K01098_IL008
K01098_IL009
________________

Nenahrávať
________________
K01711_004
K05111 IL002
________________
```

**Comment by macholiver** [comment]
Záznamy sú opäť nahrané.

**Comment by VojtechSicha** [comment]
@macholiver Takže to po úpravách zabralo
