### ISSUE TITLE
Vyhledávání obecně

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#72]
Nerozlišovat velká a malá písmena. Př. BCBT vs bcbt. V druhém případě se nic nevyhledá.

**Comment by Kretiss** [comment]
@VojtechSicha Kterých polí se to má týkat?

**Comment by VojtechSicha** [comment]
@Kretiss aktuálně mi políčko pro vyhledávání na testu nebere žádný dotaz.

**Comment by VojtechSicha** [comment]
@Kretiss toto stále nefunguje. Týká se při vyhledávání podle Vše a ID záznamu (podle ID ve všech záložkách)

**Comment by Kretiss** [comment]
@VojtechSicha týká se to admina nebo normální appky? Mi to v normální appce funguje

**Comment by VojtechSicha** [comment]
@Kretiss Týká se to aplikace (i testu). Když zadám bcbt, nedostanu žádný výsledek. Když zadám BCBT záznamy mi to nabídne. Viz obrázky:

![BCBT malá](https://github.com/LIBCAS/e-ilustrace/assets/127321356/92167a87-60cf-42a8-98a3-275fb2557aa7)
![BCBT velká](https://github.com/LIBCAS/e-ilustrace/assets/127321356/db72bb78-811d-42c9-9515-401e7cb84c7f)

**Comment by Kretiss** [comment]
@macholiver změnit identifier na FTXF

**Comment by macholiver** [comment]
@Kretiss Na TESTe zmenené.

**Comment by VojtechSicha** [comment]
@macholiver Skvělé, může na produkci.

**Comment by macholiver** [comment]
@VojtechSicha nasadene
