### ISSUE TITLE
Témata

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#73]
Počty u jednotlivých kategorií by se měly dynamicky měnit podle zúžení dotazu.

Vyhledávací okénko by mělo našeptávat podobně jako u vyhledávání. Mělo by nabízet vše, co je vyobrazené (osoby, témata, vyobrazená místa)

**Comment by Kretiss** [comment]
@macholiver máš tohle jak udělat na BE?

**Comment by macholiver** [comment]
@Kretiss 
Na ten pocet u kategorii ti asi mozem spravit endpoint do ktoreho budes posielat Params a vrati ti pocet. Budes ho ale musiet volat pre kazdu kategoriu zvlast. To znamena ze musime okresat co vsetko potrebujeme mat zaindexovane, pretoze s tym ako to je teraz plne nam pre 9 Tem urcite padne cela appka na nedostatok RAMky

**Comment by macholiver** [comment]
@Kretiss 
Pridal som ```POST /theme/count-by-params``` Ocakava ako payload Params, podobne ako klasicky ```list```. Funguje rovnako ako ```/count```. Payload nie je required, takze by mal nahradit aj povodny ```/count```. Nakoniec plati, ze ho nemusis volat zvlast pre kazdu temu.

**Comment by Kretiss** [comment]
Použít AND a ne OR pro filtraci

**Comment by VojtechSicha** [comment]
@macholiver Může jít na produkci.
