### ISSUE TITLE
ICONCLASS

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#74]
Vyhledávací roletka Titulek - přejmenovat na Název. IC jméno přejmenovat na IC termín. Uspořádat nabídku roletek v posloupnosti IC kód, IC termín , Název, ID.

Vyhledává také v závorkách? Př. 25G41(ROSE) nenajde.

Čeština v levé nabídce!

**Comment by macholiver** [comment]
@Kretiss 
Zatvorky sa taktiez indexuju ako text.
<img width="993" alt="image" src="https://github.com/LIBCAS/e-ilustrace/assets/84499955/53442dd8-fd92-429d-9cac-61acaac4b19e">
