### ISSUE TITLE
Vizuál záznamů - chyba v zobrazení náhledů v galerii výsledků

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#79]
Narazili jsme na podivné zobrazení záznamu viz obrázek.

![Miniatura](https://github.com/LIBCAS/e-ilustrace/assets/127321356/db4d5c51-1747-4408-9481-d1b07fdbb8e7)

**Comment by Kretiss** [comment]
@VojtechSicha Jednalo se o záznam K02867_IL162? Jde to z toho obrázku blbě přečíst

**Comment by VojtechSicha** [comment]
@macholiver Může na produkci
