### ISSUE TITLE
Mirador - zobrazení okna

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#80]
Na některých obrazovkách se Mirador zobrazuje bez prvních písmen ikon u nápovědy viz obrázek.

![Mirador ikony](https://github.com/LIBCAS/e-ilustrace/assets/127321356/cf29b4fa-5f5b-44e4-a724-e2a8a25f1e51)

**Comment by VojtechSicha** [comment]
@Kretiss Stále stejné, ale je to detail, který případně zkousneme.

**Comment by Kretiss** [comment]
Můžeme zavřít? Tohle je věc Mirádoru

**Comment by VojtechSicha** [comment]
@Kretiss Ano stejný problém jsem viděl např. i v Manuscriptoriu.
