### ISSUE TITLE
Mirador – prohlížeč chybí u některých záznamů ilustrací 

### ISSUE THREAD

**Issue by Veronikasladka** [LIBCAS/e-ilustrace#82]
Prosím můžete zjistit, proč chybí prohlížeč Mirador u ilustrací s číslem K06009; stejně tak je nemohu najít ve VISE @macholiver @Kretiss 

<img width="1014" alt="Snímek obrazovky 2023-11-19 v 18 59 43" src="https://github.com/LIBCAS/e-ilustrace/assets/77391424/6e29dddb-cee2-44b1-82a3-27959206a356">

**Comment by Kretiss** [comment]
@VojtechSicha vyřešeno, chybělo nasadit aplikaci na test
