### ISSUE TITLE
Mirador - Index

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#85]
@macholiver V indexu Miradoru u knihy nezobrazujeme údaje k jednotlivým ilustracím.
![Mirador Biblissima](https://github.com/LIBCAS/e-ilustrace/assets/127321356/cf5e75b9-4859-4b70-8ff1-b7010964a6dc)
![Mirador EIL](https://github.com/LIBCAS/e-ilustrace/assets/127321356/9caf2eb5-35a9-454b-ba56-4b1bb876fd1e)

**Comment by macholiver** [comment]
@VojtechSicha Prosim definovat co ma byt v indexe. Aktualne pre ukazku pridany nazov ilustracie, identifier a autor.
