### ISSUE TITLE
Administrativní prostředí (super admin)

### ISSUE THREAD

**Issue by VojtechSicha** [LIBCAS/e-ilustrace#95]
@macholiver Lze zřídit superadmina pro možnost např. rušit výstavy jiných, mrtvé účty spod.

**Comment by Kretiss** [comment]
Tady by to chtělo probrat, kde se tohle všechno má dít. Má to být v administrační části aplikace? Co všechno teda chcete měnit?

**Comment by VojtechSicha** [comment]
@Kretiss Zaměřím se na to a připravím podklady.

**Comment by Kretiss** [comment]
- [ ] Smazání účtu trvale -> ADMIN může usera, SUPER_ADMIN ADMINA
- [ ] Skrytí výstavy, smazání výstavy

**Comment by VojtechSicha** [comment]
@Kretiss Více mě k tomu nenapadá.

**Comment by macholiver** [comment]
@macholiver 
Osetrit referencie na uzivatela v inych entitach po odmazani.

**Comment by Kretiss** [comment]
@macholiver přidat roli ADMIN do /publish endpointu

**Comment by VojtechSicha** [comment]
@Kretiss 

a) Podařilo se mi smazat nežádoucího uživatele.
b) Podařilo se mi skrýt publikovanou výstavu jiného uživatele.

c) Smazat výstavu se mi nepodařilo.

**Comment by Kretiss** [comment]
@VojtechSicha Mazat výstavy může jenom SUPER_ADMIN. Je to takhle v pořádku nebo to máme upravit?

**Comment by VojtechSicha** [comment]
@Kretiss  Rozumím. Jen pro pořádek, kdo je superadmin? Ten teprve vznikne?

**Comment by Kretiss** [comment]
@VojtechSicha Prozatím nikdo, je třeba se domluvit

**Comment by VojtechSicha** [comment]
@Kretiss Můžeme mít dva superadminy?

**Comment by macholiver** [comment]
@VojtechSicha 
Superadminov mozete mat kolko chcete. Vasmu uctu tuto rolu nastavim ja a vy mozete nasledne tuto rolu pridavat dalej.

**Comment by VojtechSicha** [comment]
@macholiver To je dobrá zpráva. Já bych to stejně viděl jen na dva, max tři.  Určitě já a účet kolegyně Heilandové z NK lucie.heilandova@nkp.cz

**Comment by macholiver** [comment]
@VojtechSicha nasadene a rola superadmin nastavena

**Comment by VojtechSicha** [comment]
@macholiver Děkuji. Uzavírám.
